apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: channel-intelligence-e2e-tests
  title: channel-intelligence-e2e-tests
  description: E2E tests for messaging channel selection
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/channel-intelligence-e2e-tests
    buildkite.com/project-slug: twilio/twilio-internal-channel-intelligence-e2e-tests
    github.com/project-slug: twilio-internal/channel-intelligence-e2e-tests
    jira/project-key: RTR
    pagerduty.com/service-id: PUHVBS6
    twilio.com/email: team_omnichannel-routing-engineering@twilio.com
    twilio.com/ldap-group: team_omnichannel-routing-engineering
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-sms-routing
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/channel-intelligence-e2e-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-channel-intelligence-e2e-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/channel-intelligence-e2e-tests-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-734
  system: omnichannel-intelligence