apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dip
  title: dip
  description: DIP service for number lookups.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/dip/dip
    buildkite.com/project-slug: twilio/dip-number-info-service
    github.com/project-slug: dip/dip
    github.com/team-slug: team_dip-pricing
    pagerduty.com/service-id: P3CXC64
    twilio.com/email: team_dip-pricing@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/ldap-group: team_dip-pricing
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-dip-pricing
  links:
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382763489
  - title: Deployment Repository
    url: https://github.com/twilio-internal/dip-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/dip-number-info-service
  - title: IaC Repository
    url: https://code.hq.twilio.com/dip/dip-terraform
spec:
  type: service
  lifecycle: production
  owner: group:sup-org-2688
  system: dip
  dependsOn:
  - component:default/id-encrypt-decrypt-service
  - component:default/ud-entity-schema-api
  - component:default/sn-messaging-decision-rates
  - component:default/eventbus
  - component:default/dsg-threat-network