apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-beepsend-admin
  title: messaging-beepsend-admin
  description: Administration portal for the beepsend infrastructure
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/beepsend/edge-admin-ui
    github.com/project-slug: beepsend/edge-admin-ui
    pagerduty.com/service-id: PPEE63X
    twilio.com/email: sms-ui@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '4'
  tags:
  - messaging
  links:
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382768858
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-734
  system: messaging-routing-service