apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-routing-bff
  title: messaging-routing-bff
  description: Backend for frontend for messaging routing
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-routing-bff
    buildkite.com/project-slug: twilio/twilio-internal-messaging-routing-bff
    github.com/project-slug: twilio-internal/messaging-routing-bff
    jira/project-key: SMSUI
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_sms-ui@twilio.com
    twilio.com/ldap-group: team_sms-ui
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: help-snx
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-routing-bff-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-messaging-routing-bff
  - title: IaC Repository
    url: https://github.com/twilio-internal/messaging-routing-bff-iac
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-734
  system: messaging-routing-service