kind: Component
spec:
  type: service
  owner: "group:default/sup-org-734"
  system: messaging-routing-service
  lifecycle: production
metadata:
  name: messaging-beepsend-connect
  tags:
    - messaging
  links:
    -
      url: "https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382769740"
      title: Runbook
  title: messaging-beepsend-connect
  annotations:
    twilio.com/email: sms-ui@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 4
    pagerduty.com/service-id: PPEE63X
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
  description: (UI only role) Beepsends legacy customer portal. Used by customers for account management and basic messaging functionality
apiVersion: backstage.io/v1alpha1