apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-routing-integration-tests
  title: messaging-routing-integration-tests
  description: Messaging routing E2E integration tests.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/routing-integration-tests
    buildkite.com/project-slug: twilio/messaging-routing-integration-tests
    github.com/project-slug: messaging/routing-integration-tests
    twilio.com/github-server: code.hq.twilio.com
    jira/project-key: ROC
    pagerduty.com/service-id: PVB14I4
    twilio.com/email: team_routing-core@twilio.com
    twilio.com/ldap-group: team_routing-core
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: help-routing-core
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-routing-integration-tests-deploy
  - title: Buildkite Pipeline
    url: https://buildkite.com/twilio/messaging-routing-integration-tests
  tags:
  - messaging
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-734
  system: messaging-routing-service