kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2688"
  system: dip
  lifecycle: production
metadata:
  name: messaging-dip-auxiliary
  links:
    -
      url: "https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382763489"
      title: Runbook
    -
      url: "https://github.com/twilio-internal/messaging-dip-auxiliary-deploy"
      title: Deployment Repository
  title: messaging-dip-auxiliary
  annotations:
    twilio.com/email: team_dip-pricing@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P3CXC64
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
  description: Instance of dip for use by components not involved in processing real-time messages (e.g., Lookups API, billing)
apiVersion: backstage.io/v1alpha1