apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-dip-provider
  title: messaging-dip-provider
  description: Service acting as an internal dip provider for the dip service for static dip rules for testing purposes
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/dip/dip-provider
    buildkite.com/project-slug: twilio/dip-dip-provider
    github.com/project-slug: dip/dip-provider
    jira/project-key: DIPPRC
    pagerduty.com/service-id: P3CXC64
    twilio.com/data-classification: restricted
    twilio.com/email: team_dip-pricing@twilio.com
    twilio.com/eu-available: "false"
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/internet-facing: "false"
    twilio.com/ldap-group: team_dip-pricing
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "5"
    twilio.com/sla-impacting: "false"
    twilio.com/slack-channel-name: "#eng-dip-pricing"
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/messaging-dip-provider-deploy
    - title: Buildkite Pipeline
      url: https://buildkite.com/twilio/dip-dip-provider
spec:
  type: service
  lifecycle: production
  owner: group:sup-org-2688
  system: dip