apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: omnichannel-conversion-rate
  title: omnichannel-conversion-rate
  description: Omnichannel conversion rate role
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/sms/omnichannel-conversion-rate
    buildkite.com/project-slug: twilio/twilio-internal-omnichannel-conversion-rate
    github.com/project-slug: sms/omnichannel-conversion-rate
    github.com/team-slug: team_omnichannel-routing-engineering
    pagerduty.com/service-id: PUHVBS6
    twilio.com/email: team_omnichannel-routing-engineering@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/ldap-group: team_real-time-routing
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: '#eng-sms-routing'
  links:
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/563118088
  - title: Buildkite Pipeline
    url: https://buildkite.com/twilio/twilio-internal-omnichannel-conversion-rate
  - title: Deployment Repository
    url: https://github.com/twilio-internal/omnichannel-conversion-rate-deploy
spec:
  type: service
  lifecycle: production
  owner: group:sup-org-734
  system: omnichannel-intelligence