apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: route-conversion-rate
  title: route-conversion-rate
  description: A Spark app that aggregates route conversion data for the automated route ranking system
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/route-conversion-rate
    buildkite.com/project-slug: twilio/twilio-internal-route-conversion-rate
    github.com/project-slug: twilio-internal/route-conversion-rate
    github.com/team-slug: team_real-time-routing
    pagerduty.com/service-id: PUHVBS6
    twilio.com/email: team_real-time-routing@twilio.com
    twilio.com/ldap-group: team_real-time-routing
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: '#eng-sms-routing'
  links:
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/800818271
  - title: Buildkite Pipeline
    url: https://buildkite.com/twilio/twilio-internal-route-conversion-rate
  - title: Deployment Repository
    url: https://github.com/twilio-internal/route-conversion-rate-deploy
spec:
  type: service
  lifecycle: production
  owner: group:sup-org-734
  system: automated-route-ranking