apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: netbox
  title: NetBox (IPAM and DCIM)
  description: Twilio IPAM and DCIM service
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/netbox
    buildkite.com/project-slug: twilio/twilio-internal-backstage-twilio
    github.com/project-slug: twilio-internal/netbox
    jira/project-key: SNIP
    pagerduty.com/service-id: P92CX01
    twilio.com/email: team_super-network-infrastructure-platform@twilio.com
    twilio.com/ldap-group: super-network-infrastructure-platform
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-channel-name: help-sn-infrastructure-platform
    twilio.com/data-classification: restricted
    twilio.com/internet-facing: "false"
    twilio.com/eu-available: "false"
    twilio.com/sla-impacting: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-sox: "false"
  links:
    - title: Buildkite Pipeline
      url: https://buildkite.com/sendgrid/terraform-netbox
    - title: Deployment Repository
      url: https://github.com/twilio-internal/netbox-deploy
  tags:
    - dcim
    - ipam
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-640
  system: network-asset-management