apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: netbox-db-backup
  title: netbox-db-backup
  description: Repository created by Backstage. It creates a Netbox database backup, upload to S3 and restores it in another account.
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/netbox-db-backup
    buildkite.com/project-slug: twilio/twilio-internal-netbox-db-backup
    github.com/project-slug: twilio-internal/netbox-db-backup
    jira/project-key: SNIP
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_super-network-infrastructure-platform@twilio.com
    twilio.com/ldap-group: team_super-network-infrastructure-platform
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: replace-me
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/netbox-db-backup-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-netbox-db-backup
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-640
  system: network-asset-management