apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sbc-virtual-desktop
  title: SBC Virtual Desktop
  description: SBC Virtual Desktop host
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/network_tooling_apis_tfc_repo
    buildkite.com/project-slug: twilio/twilio-internal-backstage-twilio
    github.com/project-slug: twilio-internal/network_tooling_apis_tfc_repo
    jira/project-key: SNIP
    twilio.com/email: team_super-network-infrastructure-platform@twilio.com
    twilio.com/ldap-group: super-network-infrastructure-platform
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: help-sn-infrastructure-platform
  links: []
  tags:
  - sbc
  - virtual-desktop
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-640
  system: sbc