apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sbc-pcaps-producer
  title: sbc-pcaps-producer
  description: Produce PCAP files from SIP Call session logs
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/sbc-pcaps-producer
    github.com/project-slug: super-network/sbc-pcaps-producer
    pagerduty.com/service-id: P92CX01
    twilio.com/email: team_super-network-infrastructure-platform@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/sbc-pcaps-producer-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-640
  system: sbc
  dependsOn:
  - component:default/dp-elasticsearch-gateway
  - component:default/eventbus
  - component:default/data-producer-api
  - component:default/ud-entity-schema-api