apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tnx-directory-cache
  title: tnx-directory-cache
  description: a RESTful caching service for all tnx-directory related api; to be
    used in voice flows
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/tnx-directory-cache
    github.com/project-slug: twilio-internal/tnx-directory-cache
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
    pagerduty.com/service-id: PGQ19ZB
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/email: sn-interconnect@twilio.com
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/tnx-directory-cache-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-640
  system: tnx-directory