apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1586"
metadata:
  name: acceptance_event_consumer
  title: acceptance_event_consumer
  description: "acceptance_event_consumer service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/acceptance_event_consumer