apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: amc
  title: amc
  description: "AMC is a sidecar service to apid and is deployed as a such in Apid's kube pod."
  tags:
    - email
    - ep-delivery
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/amc/blob/main/RgiEADME.md
    github.com/project-slug: sendgrid/amc
    backstage.io/source-location: url:https://github.com/sendgrid/amc
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    pagerduty.com/service-id: PPVKLCL
    twilio.com/slack-id: CDJCC7ETD