apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1673"
  system: email-delivery
metadata:
  name: apid
  title: apid
  description: "apid service is API Daemon enforcing an abstraction on persistence of the Data Model, specifically MySQL"
  tags:
    - email
    - ep-delivery
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/apid
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/apid/blob/master/README.md
    github.com/project-slug: sendgrid/apid
    pagerduty.com/service-id: PXT266D
    twilio.com/email: email-ep-delivery@twilio.com
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: CDJCC7ETD