apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: aurora-dbmain-proxysql-gitops
  title: aurora-dbmain-proxysql-gitops
  description: "GitOps configuration for Aurora DB Main ProxySQL."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/aurora-dbmain-proxysql-gitops
  tags:
    - email-db
    - email-dna