apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: autoseeder-docker
  title: autoseeder-docker
  description: "Docker configuration for autoseeder service."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/autoseeder-docker
  tags:
    - email-db
    - email-dna