apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: chef
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: chef-sendgrid_postfix
  title: chef-sendgrid_postfix
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/chef-sendgrid_postfix/blob/master/README.md
    pagerduty.com/service-id: PPVKLCL
    backstage.io/source-location: url:https://github.com/sendgrid-ops/chef-sendgrid_postfix
    github.com/project-slug: sendgrid-ops/chef-sendgrid_postfix
    twilio.com/slack-id: CDJCC7ETD