apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: chef
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: chef-go_relayd
  title: chef-go_relayd
  description: "chef-go_relayd deploys the SendGrid go_relayd daemon.."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid-ops/chef-go_relayd/blob/master/README.md
    backstage.io/source-location: url:https://github.com/sendgrid-ops/chef-go_relayd
    github.com/project-slug: sendgrid-ops/chef-go_relayd
    twilio.com/slack-id: CDJCC7ETD