apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: chef
  lifecycle: production
  owner: "group:default/sup-org-1658"
  system: email-v2-api
metadata:
  name: chef-mysql_senderauth
  title: chef-mysql_senderauth
  tags:
    - email
    - ep-configuration
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/chef-mysql_senderauth
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/chef-mysql_senderauth/blob/main/README.md
    github.com/project-slug: sendgrid/chef-mysql_senderauth
    twilio.com/email: email-ep-configuration@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: C01EVRFDP0T