apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1673"
metadata:
  name: chef-sendgrid_redisio_postoffice
  title: chef-sendgrid_redisio_postoffice
  description: "chef-sendgrid_redisio_postoffice service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/chef-sendgrid_redisio_postoffice