apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
metadata:
  name: consul-prom-metrics-exporter
  title: consul-prom-metrics-exporter
  description: consul-prom-metrics-exporter service for SendGrid integration.
  tags:
  - email-edge
  - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/consul-prom-metrics-exporter
    twilio.com/email: email-ep-edge@twilio.com
    twilio.com/slack-id: CF7MT3UAC
    jira/project-key: EEDGE
    github.com/project-slug: sendgrid/consul-prom-metrics-exporter