apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1658"
  system: email-v2-api
metadata:
  name: crud_alerts_acceptance
  title: crud_alerts_acceptance
  tags:
    - email
    - ep-configuration
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/crud_alerts_acceptance
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/crud_alerts_acceptance/blob/master/README.md
    github.com/project-slug: sendgrid/crud_alerts_acceptance
    twilio.com/email: email-ep-configuration@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: C01EVRFDP0T