apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: dbops-mysql-seed
  title: dbops-mysql-seed
  description: "Database operations service for MySQL seeding."
  tags:
    - email-db
    - email-dna
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/dbops-mysql_seed