apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
  system: geopod
metadata:
  name: ebs-modifier
  title: ebs-modifier
  description: "The EBS Modifier is a shell script that will look for an EBS volume that was created by Kubernetes with a specific PVC name and attempt to upgrade that volume to gp3."
  tags:
    - email
    - geopod
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-edge@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/ebs-modifier/blob/main/README.md
    pagerduty.com/service-id: PH5E2YF
    backstage.io/source-location: url:https://github.com/sendgrid/ebs-modifier
    github.com/project-slug: sendgrid/ebs-modifier
    twilio.com/slack-id: CF7MT3UAC