apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: ee_time
  title: ee_time
  description: "ee_time service is an event consumer to intelligently metric email pipeline end-to-end time."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/ee_time/blob/main/README.md
    pagerduty.com/service-id: PPVKLCL
    backstage.io/source-location: url:https://github.com/sendgrid/ee_time
    github.com/project-slug: sendgrid/ee_time
    twilio.com/slack-id: CDJCC7ETD