apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: ei-delivery-global-alerts
  title: ei-delivery-global-alerts
  description: "ei-delivery-global-alerts is helm chart to deploy global alerts that are not specific to any existing service."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/ei-delivery-global-alerts/blob/main/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/ei-delivery-global-alerts
    github.com/project-slug: sendgrid/ei-delivery-global-alerts
    twilio.com/slack-id: CDJCC7ETD