apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1658"
metadata:
  name: eimoogle-terraform-modules
  title: eimoogle-terraform-modules
  description: "eimoogle-terraform-modules service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/eimoogle-terraform-modules