apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1505"
metadata:
  name: expert-insights-pdf
  title: expert-insights-pdf
  description: "expert-insights-pdf service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/expert-insights-pdf