apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
  system: geopod
metadata:
  name: geopod-synthetic-check
  title: geopod-synthetic-check
  description: "geopod-synthetic-check performs synthetic check for Geopod. It will periodically check geopod endpoints for their healthiness."
  tags:
    - email
    - geopod
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-edge@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/geopod-synthetic-check/blob/main/README.md
    pagerduty.com/service-id: PH5E2YF
    backstage.io/source-location: url:https://github.com/sendgrid/geopod-synthetic-check
    github.com/project-slug: sendgrid/geopod-synthetic-check
    twilio.com/slack-id: CF7MT3UAC