apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
  system: geopod
metadata:
  name: geopod-monitor
  title: geopod-monitor
  description: "geopod-monitor service is a collection of tools for monitoring the Geopod."
  tags:
    - email
    - geopod
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-edge@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/geopod-monitor/blob/main/README.md
    pagerduty.com/service-id: PH5E2YF
    backstage.io/source-location: url:https://github.com/sendgrid/geopod-monitor
    github.com/project-slug: sendgrid/geopod-monitor
    twilio.com/slack-id: CF7MT3UAC