apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1586"
metadata:
  name: go-smtp-debugging
  title: go-smtp-debugging
  description: "go-smtp-debugging service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/go-smtp-debugging