apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1586
  system: geopod
metadata:
  name: helm-geopod-envoy
  title: helm-geopod-envoy
  description: "helm-geopod-envoy for the envoy proxies used for communication between the k8s general clusters."
  tags:
    - email
    - geopod
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-edge@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/helm-geopod-envoy/blob/main/README.md
    pagerduty.com/service-id: PH5E2YF
    backstage.io/source-location: url:https://github.com/sendgrid/helm-geopod-envoy
    github.com/project-slug: sendgrid/helm-geopod-envoy
    twilio.com/slack-id: CF7MT3UAC