apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
metadata:
  name: helm-teapot-inbucket
  title: helm-teapot-inbucket
  description: helm-teapot-inbucket service for SendGrid integration.
  tags:
  - email-core
  - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-teapot-inbucket
    twilio.com/email: email-ep-core@twilio.com
    twilio.com/slack-id: CUJT2EZ5F
    jira/project-key: ECORE
    github.com/project-slug: sendgrid/helm-teapot-inbucket