apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: helm-go_relayd
  title: helm-go_relayd
  description: "helm-go_relayd is Helm Chart for Go Relayd (Proxy)."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/helm-go_relayd/blob/master/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/helm-go_relayd
    github.com/project-slug: sendgrid/helm-go_relayd
    twilio.com/slack-id: CDJCC7ETD