apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1586"
metadata:
  name: helm-mp-kafka-mirrormaker
  title: helm-mp-kafka-mirrormaker
  description: "helm-mp-kafka-mirrormaker service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-mp-kafka-mirrormaker