apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: helm-sink
  title: helm-sink
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/helm-sink/blob/main/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/helm-sink
    github.com/project-slug: sendgrid/helm-sink
    twilio.com/slack-id: CDJCC7ETD