apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-nlvx-cleanup-data
  title: helm-nlvx-cleanup-data
  description: "Helm NLVX Cleanup Data service for SendGrid integration."
  tags:
    - email
    - mc-nlvx
  name: helm-nlvx-cleanup-data