apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: helm-bounce_purge
  title: helm-bounce_purge
  description: "helm-bounce_purge service for SendGrid integration."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/helm-bounce_purge/blob/main/README.md
    pagerduty.com/service-id: PPVKLCL
    backstage.io/source-location: url:https://github.com/sendgrid/bcr
    github.com/project-slug: sendgrid/helm-bounce-purge
    twilio.com/slack-id: CDJCC7ETD