apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
metadata:
  name: helm-envoy-forwarder
  title: helm-envoy-forwarder
  description: helm-envoy-forwarder service for SendGrid integration.
  tags:
  - email-core
  - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-envoy-forwarder
    twilio.com/email: email-ep-core@twilio.com
    twilio.com/slack-id: CUJT2EZ5F
    jira/project-key: ECORE
    github.com/project-slug: sendgrid/helm-envoy-forwarder