apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: "group:default/sup-org-1673"
  system: email-delivery
metadata:
  name: helm-parsesink
  title: helm-parsesink
  tags:
    - email
    - ep-delivery
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-parsesink
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/helm-parsesink/blob/master/README.md
    github.com/project-slug: sendgrid/helm-parsesink
    twilio.com/email: email-ep-delivery@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: CDJCC7ETD