apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1505"
metadata:
  name: k8s-ei-stats-alertmanager-config
  title: k8s-ei-stats-alertmanager-config
  description: "k8s-ei-stats-alertmanager-config service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/k8s-ei-stats-alertmanager-config