apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-kafkarelay-ev-events
  title: k8s-kafkarelay-ev-events
  description: This is the Kafka Relay charts/config for EV. This Kafka Relay will be taking EV events and sending them to MP-Events.
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/k8s-kafkarelay-ev-events
    buildkite.com/project-slug: sendgrid/k8s-kafkarelay-ev-events
    github.com/project-slug: sendgrid/k8s-kafkarelay-ev-events
    twilio.com/in-scope-soc2: 'true'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  tags:
  - soc2
  - sox
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-1658
  system: email-validation