apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
metadata:
  name: k8s-eventsink
  title: k8s-eventsink
  description: k8s-eventsink service for SendGrid integration.
  tags:
  - email-core
  - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/k8s-eventsink
    twilio.com/email: email-ep-core@twilio.com
    twilio.com/slack-id: CUJT2EZ5F
    jira/project-key: ECORE
    github.com/project-slug: sendgrid/k8s-eventsink