apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logs-analytics-api
  title: logs-analytics-api
  description: Exposes Logs and Analytics APIs
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/logs-analytics-api
    buildkite.com/project-slug: twilio/twilio-internal-logs-analytics-api
    github.com/project-slug: twilio-internal/logs-analytics-api
    jira/project-key: SOA
    pagerduty.com/service-id: PZ8SR86
    twilio.com/email: team_twlo-operational-analytics@twilio.com
    twilio.com/ldap-group: team_twlo-operational-analytics
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: flex-insights-alerts
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/logs-analytics-api-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-logs-analytics-api
  - title: IaC Repository
    url: https://github.com/twilio-internal/logs-analytics-api-iac
  tags:
  - stateful
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1505
  system: twlo-operational-analytics