apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/nlvx-stats-aggregator
  title: nlvx-stats-aggregator
  description: "nlvx-stats-aggregator service for SendGrid integration."
  tags:
    - email
    - mc-nlvx
  name: nlvx-stats-aggregator