apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/nlvx-noderouter
  title: nlvx-noderouter
  description: "nlvx-noderouter service for SendGrid integration."
  tags:
    - email
    - mc-nlvx
  name: nlvx-noderouter