apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: orchestrator-docker
  title: orchestrator-docker
  description: "Docker configuration for orchestrator service."
  tags:
    - email-db
    - email-dna
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/orchestrator-docker