apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1673"
  system: email-delivery
metadata:
  name: postman
  title: postman
  description: "postman is the stateless architecture MTA for Twilio SendGrid."
  tags:
    - email
    - ep-delivery
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/postman
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/postman/blob/main/README.md
    github.com/project-slug: sendgrid/postman
    twilio.com/email: email-ep-delivery@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: CDJCC7ETD