apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: postoffice-deduper-node-tools
  title: postoffice-deduper-node-tools
  description: "postoffice-deduper-node-tools are tools for verifying Postoffice Deduper Nodes, config formatting."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/postoffice-deduper-node-tools/blob/main/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/postoffice-deduper-node-tools
    twilio.com/slack-id: CDJCC7ETD