apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: schema-bounce
  title: schema-bounce
  description: "Schema service for bounce handling."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/schema_bounce
  tags:
    - email-db
    - email-dna