apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: schema-cas
  title: schema-cas
  description: "CAS schema management service."
  tags:
    - email-db
    - email-dna
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/schema_cas