apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: schema-uvs
  title: schema-uvs
  description: "schema-uvs service for database management."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/schema_uvs
  tags:
    - email-db
    - email-dna