apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: schema-compliance
  title: schema-compliance
  description: "Schema compliance service for database management."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/schema_compliance
  tags:
    - email-db
    - email-dna