apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: styx
  title: styx
  description: "styx Styx Service provides the endpoints that satisfy business functions or internal requirements for sharing abuse feedback data between Spamhaus and Email Service Providers (ESPs)."
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/styx/blob/main/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/styx
    github.com/project-slug: sendgrid/styx
    twilio.com/slack-id: CDJCC7ETD