apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1673"
  system: email-delivery
metadata:
  name: sup
  title: sup
  description: "The suppression writer system consumes events from the mp-events topic of the mail pipeline kafka cluster, and writes the supported events to the respective database through ProxySQL."
  tags:
    - email
    - ep-delivery
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/sup
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/sup/blob/main/README.md
    github.com/project-slug: sendgrid/sup
    twilio.com/email: email-ep-delivery@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: CDJCC7ETD