kind: API
spec:
  type: openapi
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
  lifecycle: production
  definition: "openapi: 3.0.3
security:
  # First option: bypass key + JWT (skip signature validation)
  - BypassKeyAuth: [ ]
    SGGatewayJWTAuth: [ "messages.read" ]
  # Second option: JWT (with signature validation)
  - SGGatewayJWTAuth: [ "messages.read" ]
  # Third option: API Key (for client compatibility with public endpoint)
  - APIKeyAuth: [ ]

paths:
  /v3/logs/{sg_message_id}:
    get:
      summary: Get all details for the specified message (Email Logs format)
      x-ogen-operation-group: EmailLogs
      operationId: EmailLogsGetMessageById
      security:
        # First option: bypass key + JWT with messages.read or email_activity.read scope
        - BypassKeyAuth: [ ]
          SGGatewayJWTAuth: [ "messages.read" ]
        - BypassKeyAuth: [ ]
          SGGatewayJWTAuth: ["email_activity.read" ]
        # Second option: JWT with messages.read or email_activity.read scope (with signature validation)
        - SGGatewayJWTAuth: [ "messages.read" ]
        - SGGatewayJWTAuth: [ "email_activity.read" ]
        # Third option: API Key (for client compatibility with public endpoint)
        - APIKeyAuth: [ ]
      parameters:
        - name: sg_message_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the message you are requesting details for.
        - name: "subuser"
          in: query
          description: |
            For requests coming from an authenticated parent user principal,
            this argument must be passed if the message belongs to a subuser.
            Only 1 item is allowed in this list, but we make it a list for forward compatibility.
            Even though all SG User IDs are numeric, we pass them as strings for forward compatibility,
            if user IDs ever change to non-numeric values.
          schema:
            type: string
            format: '^\d+$'
      responses:
        '200':
          description: Detailed information for the specified message, including all events related to the message
          content:
            application/json:
              schema:
                $ref: 'email_logs.yaml#/components/schemas/EmailLogsGetMessageByIdResponse'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: |
            Forbidden may be returned when trying to incorrectly access logs for another user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Message not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many requests, rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: 'Default error response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v3/logs:
    description: |
      This endpoint exposes a endpoint for retrieving multiple messages matching a given filter.
      We take a POST method instead of a GET to ensure that private data does not get leaked or logged inadvertently
      by intermediate infrastructure.
    post:
      summary: Search all messages using the provided query filters.
      x-ogen-operation-group: EmailLogs
      operationId: EmailLogsGetMessagesByFilter
      security:
        # First option: bypass key + JWT with messages.read or email_activity.read scope
        - BypassKeyAuth: [ ]
          SGGatewayJWTAuth: [ "messages.read" ]
        - BypassKeyAuth: [ ]
          SGGatewayJWTAuth: ["email_activity.read" ]
        # Second option: JWT with messages.read or email_activity.read scope (with signature validation)
        - SGGatewayJWTAuth: [ "messages.read" ]
        - SGGatewayJWTAuth: [ "email_activity.read" ]
        # Third option: API Key (for client compatibility with public endpoint)
        - APIKeyAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'email_logs.yaml#/components/schemas/EmailLogsGetMessagesByFilterRequest'

      responses:
        '200':
          description: A page of messages matching the filter.
          content:
            application/json:
              schema:
                $ref: 'email_logs.yaml#/components/schemas/EmailLogsGetMessagesByFilterResponse'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many requests, rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: 'Default error response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:

  securitySchemes:

    BypassKeyAuth:
      type: apiKey
      in: header
      name: X-Jwt-Bypass-Key
      description: Bypass key for internal service authentication. If a valid bypass key is provided, then JWT signature validation will be skipped in `SGGatewayJWTAuth`.

    SGGatewayJWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication using JWT bearer token. Validates the JWT coming from SG Gateway

    APIKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: APIKey
      description: Authentication using API token. Used for compatibility with public endpoint.

  schemas:

    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: Standard SendGrid error response.

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message.
        field:
          type: string
          description: (Optional) The field that caused the error.
      required:
        - message
"
metadata:
  name: email-logs-api
  title: Email Logs API (/v3/logs)
  description: Email Logs API (/v3/logs)
apiVersion: backstage.io/v1alpha1
---
kind: API
spec:
  type: openapi
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
  lifecycle: production
  definition: "openapi: 3.0.3
info:
  title: Twilio Email Logs and Statistics API
  version: "0.0.0"  # we are not really maintaining the version number here
  description: API for querying email logs and email statistics

servers:
  - description: |
      Production endpoint that load-balances via Route53 over global data residency regions (us-east-1, us-east-2).
      This is for EASE / Email Logs endpoints only.
      us-east-1 and us-east-2 both contain the entire data set, so either region can be used to query all data.
    url: https://global.statsapi-prod.sendgrid.tech
  - description: prod-us-east-1
    url: https://statsapi-ing.general-prod-a.us-east-1.aws.k8s.sendgrid.net
  - description: prod-us-east-2
    url: https://statsapi-ing.general-prod-a.us-east-2.aws.k8s.sendgrid.net
  - description: Load-balanced over global data residency regions in staging (only us-east-2)
    url: https://global.statsapi-staging.sendgrid.tech
  - description: stage-us-east-2
    url: https://statsapi-ing.general-stage-a.us-east-2.aws.k8s.sendgrid.net

security:
  # First option: bypass key + JWT (skip signature validation)
  - BypassKeyAuth: [ ]
    SGGatewayJWTAuth: [ "messages.read" ]
  # Second option: JWT (with signature validation)
  - SGGatewayJWTAuth: [ "messages.read" ]
  # Third option: API Key (for client compatibility with public endpoint)
  - APIKeyAuth: [ ]

paths:
  /v3/insights:
    description: |
      This endpoint exposes a endpoint for aggregated stats matching a given filter.
      We take a POST method instead of a GET to ensure that private data does not get leaked or logged inadvertently
      by intermediate infrastructure.
    post:
      summary: Fetch aggregated email statistics based on the provided filters.
      x-ogen-operation-group: EmailInsights
      operationId: EmailInsightsQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'email_insights.yaml#/components/schemas/EmailInsightsQueryRequest'
      responses:
        '200':
          description: A page of values matching the filter.
          content:
            application/json:
              schema:
                $ref: 'email_insights.yaml#/components/schemas/EmailInsightsQueryResponse'
        '400':
          description: Bad request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: 'Default error response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:

  securitySchemes:

    BypassKeyAuth:
      type: apiKey
      in: header
      name: X-Jwt-Bypass-Key
      description: Bypass key for internal service authentication. If a valid bypass key is provided, then JWT signature validation will be skipped in `SGGatewayJWTAuth`.

    SGGatewayJWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication using JWT bearer token. Validates the JWT coming from SG Gateway

    APIKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: APIKey
      description: Authentication using API token. Used for compatibility with public endpoint.

  schemas:

    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: Standard SendGrid error response.

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message.
        field:
          type: string
          description: (Optional) The field that caused the error.
      required:
        - message
"
metadata:
  name: email-insights-api
  title: Email Insights API (/v3/insights)
  description: OpenAPI specification for Email Logs & Insights API
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: database
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
metadata:
  name: email-logs-insights-clickhouse-cloud-service
  links:
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/terraform/modules/clickhouse"
      title: Terraform Module
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/sql-schemas"
      title: SQL Schemas
  title: Email Logs & Insights ClickHouse Cloud Service
  description: ClickHouse Cloud Service to serve Email Logs & Insights
apiVersion: backstage.io/v1alpha1
---
kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
  lifecycle: production
metadata:
  name: email-logs-user-journey
  links:
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/helm/email-logs-user-journey"
      title: Helm Chart
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/cmd/user-journey"
      title: Source Code
  title: Email Logs User Journey Continuous Testing Application
  description: User journey test application for Email Logs system that validates end-to-end email event processing flows
apiVersion: backstage.io/v1alpha1
---
kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
  dependsOn:
    - resource:default/email-logs-clickhouse-cloud-service
  lifecycle: production
metadata:
  name: email-logs-clickhouse-monitor
  links:
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/helm/email-logs-clickhouse-monitor"
      title: Helm Chart
  title: Email Logs ClickHouse Monitor
  annotations:
    twilio.com/eu-available: true
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: true
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: true
    twilio.com/security-tier: 0
    twilio.com/sla-impacting: false
    twilio.com/in-scope-hipaa: false
    twilio.com/internet-facing: false
    backstage.io/source-location: "url:https://github.com/sendgrid/email-logs-clickhouse/tree/main/helm/email-logs-clickhouse-monitor/"
    twilio.com/data-classification: confidential
  description: "Service that uses sql-exporter to collect metrics from ClickHouse and exports them for Prometheus scraping.
"
apiVersion: backstage.io/v1alpha1
---
kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1505"
  system: email-logs-insights
  dependsOn:
    - resource:default/email-logs-clickhouse-cloud-service
  lifecycle: production
metadata:
  name: kafkarelay-email-logs
  links:
    -
      url: "https://github.com/sendgrid/email-logs-clickhouse/tree/main/helm/kafkarelay-email-logs"
      title: Helm Chart
  title: Email Logs - KafkaRelay
  annotations:
    twilio.com/eu-available: true
    twilio.com/in-scope-bcr: true
    twilio.com/in-scope-iso: true
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    twilio.com/in-scope-gdpr: true
    twilio.com/in-scope-soc2: true
    twilio.com/security-tier: 0
    twilio.com/sla-impacting: false
    twilio.com/in-scope-hipaa: false
    twilio.com/internet-facing: false
    backstage.io/source-location: "url:https://github.com/sendgrid/email-logs-clickhouse/tree/main/helm/kafkarelay-email-logs/"
    twilio.com/data-classification: restricted
  description: KafkaRelay deployment that ingest events from MP Kafka and writes them into ClickHouse
apiVersion: backstage.io/v1alpha1