apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
metadata:
  name: teapot-sandbox
  title: teapot-sandbox
  description: teapot-sandbox service for SendGrid integration.
  tags:
  - email-core
  - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/teapot-sandbox
    twilio.com/email: email-ep-core@twilio.com
    twilio.com/slack-id: CUJT2EZ5F
    jira/project-key: ECORE
    github.com/project-slug: sendgrid/teapot-sandbox