apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: terraform
  lifecycle: production
  owner: sup-org-1658
  system: email-v2-api
metadata:
  name: terraform-ev
  title: terraform-ev
  tags:
    - email
    - ep-configuration
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid-ops/terraform-ev
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-configuration@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid-ops/terraform-ev/blob/main/README.md
    github.com/project-slug: sendgrid-ops/terraform-ev
    twilio.com/slack-id: C01EVRFDP0T