apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: terraform
  lifecycle: production
  owner: "group:default/sup-org-1658"
  system: email-v2-api
metadata:
  name: terraform-ev-evbulk
  title: terraform-ev-evbulk
  tags:
    - email
    - ep-configuration
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-ev-evbulk
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/terraform-ev-evbulk/blob/main/README.md
    github.com/project-slug: sendgrid/terraform-ev-evbulk
    twilio.com/email: email-ep-configuration@twilio.com
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: C01EVRFDP0T