apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: terraform-twilio-aws-aurora
  title: terraform-twilio-aws-aurora
  description: "Terraform configuration for Twilio AWS Aurora."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-twilio-aws-aurora
  tags:
    - email-db
    - email-dna