apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: terraform
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: terraform-delivery_aws_budget
  title: terraform-delivery_aws_budget
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/terraform-delivery_aws_budget/blob/master/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-delivery_aws_budget
    github.com/project-slug: sendgrid/terraform-delivery_aws_budget
    twilio.com/slack-id: CDJCC7ETD