apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-nlvx-ui
  title: terraform-nlvx-ui
  description: "terraform-nlvx-ui service for SendGrid integration."
  tags:
    - email
    - mc-nlvx
  name: terraform-nlvx-ui