apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "group:default/sup-org-1505"
metadata:
  name: terraform-rts
  title: terraform-rts
  description: "terraform-rts service for SendGrid integration."
  tags:
    - email
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-rts