apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1586
  system: geopod
metadata:
  name: tolkien-keymaker
  title: tolkien-keymaker
  description: "tolkien-keymaker service generate certificates for JWT generation and validation for SGGateway authentication flow."
  tags:
    - email
    - geopod
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: email-ep-edge@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/tolkien-keymaker/blob/main/README.md
    pagerduty.com/service-id: PH5E2YF
    backstage.io/source-location: url:https://github.com/sendgrid/tolkien-keymaker
    github.com/project-slug: sendgrid/tolkien-keymaker
    twilio.com/slack-id: CF7MT3UAC