apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1673
  system: email-delivery
metadata:
  name: tracesampler
  title: tracesampler
  tags:
    - email
    - ep-delivery
  annotations:
    twilio.com/email: email-ep-delivery@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/tracesampler/blob/master/README.md
    backstage.io/source-location: url:https://github.com/sendgrid/tracesampler
    github.com/project-slug: sendgrid/tracesampler
    twilio.com/slack-id: CDJCC7ETD