apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: treaper-tf-hello-world
  title: treaper-tf-hello-world
  description: "treaper-tf-hello-world service for database management."
  tags:
    - email-db
    - email-dna
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/treaper-tf-hello-world