apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1505
metadata:
  name: treaper-go-kube-hw
  title: treaper-go-kube-hw
  description: "Treaper Go Kubernetes Hello World service."
  tags:
    - email-db
    - email-dna
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/treaper-go-kube-hw