apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: async-message-persister
  title: async-message-persister
  description: Async Message Persistence Service for ZW core

  annotations:
    backstage.io/source-location: url:https://github.com/Zipwhip/async-message-persister
    buildkite.com/project-slug: twilio/zipwhip-async-message-persister
    github.com/project-slug: zipwhip/async-message-persister
    github.com/team-slug: zipwhip/developers
    jira/component: async-message-persister
    jira/project-key: TMINFRA
    pagerduty.com/service-id: PT8ZW7U
    twilio.com/alerting-slack-channel-id-dev: "C04SQD21U9F"
    twilio.com/alerting-slack-channel-id-prod: "C01G6UDFSMV"
    twilio.com/alerting-slack-channel-id-stage: "C05Q8A3DNH3"
    twilio.com/data-classification: restricted
    twilio.com/email: team_zipwhip-core-messaging-engineering@twilio.com
    twilio.com/eu-available: "false"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "true"
    twilio.com/in-scope-sox: "true"
    twilio.com/internet-facing: "false"
    twilio.com/pd-incident-owner-schedule: P2E936R
    twilio.com/security-tier: "0"
    twilio.com/service-tier: "3"
    twilio.com/sla-impacting: "true"
    twilio.com/slack-id: "C02H6JYEM7G"
  links:
    - title: Documentation
      url: https://zipwhip.atlassian.net/wiki/spaces/COREMESSAGING/pages/1924371533/Async+Message+Persister+Service
    - title: Grafana Dashboard
      url: https://g-870ae6cc62.grafana-workspace.us-west-2.amazonaws.com/d/ckHQy4HGk/async-message-persister?orgId=1

spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-817
  system: zw-core-messaging
  dependsOn:
    - resource:default/zw-coreprod-msk-04-kafka-cluster
    - resource:default/zw-reporting-cluster