kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: beepsend-api
  lifecycle: production
metadata:
  name: beepsend-internal-api
  title: beepsend-internal-api
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 2
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: API role for the internal Beepsend api
apiVersion: backstage.io/v1alpha1