kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: sms-beepsend-price-management
  lifecycle: production
metadata:
  name: beepsend-costlist-importer
  tags:
    - sms
  title: beepsend-costlist-importer
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 4
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Importing carrier costlists
apiVersion: backstage.io/v1alpha1