apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-rest-api-edge
  title: messaging-rest-api-edge
  description: Messaging REST API Edge for ZW Core (ATT)
  tags:
    - java
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/messaging-rest-api-edge
    jira/project-key: TMINFRA
    jira/component: messaging-rest-api-edge
    buildkite.com/project-slug: twilio/twilio-messaging-rest-api-edge
    github.com/project-slug: twilio/messaging-rest-api-edge
    github.com/team-slug: twilio/messaging
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/in-scope-soc2: 'true'
    twilio.com/in-scope-iso: 'false'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    pagerduty.com/service-id: PT8ZW7U
    twilio.com/pd-incident-owner-schedule: P2E936R
    twilio.com/email: team_zipwhip-core-messaging-engineering@twilio.com
    twilio.com/internet-facing: 'false'
    twilio.com/data-classification: restricted
    twilio.com/eu-available: 'false'
    twilio.com/sla-impacting: 'true'
    twilio.com/slack-id: 'C02H6JYEM7G'
    twilio.com/alerting-slack-channel-id-prod: 'C01G6UDFSMV'
    twilio.com/alerting-slack-channel-id-stage: 'C05Q8A3DNH3'
    twilio.com/alerting-slack-channel-id-dev: 'C04SQD21U9F'
  links:
    - title: Docuemtation
      url: https://twilio-productivity.atlassian.net/wiki/spaces/MSG/pages/743645738/Runbook+messaging-rest-edge+service
spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-817
  system: zw-core-messaging
  dependsOn:
    - resource:default/zw-coreprod-msk-aggregator-kafka-cluster
    - resource:default/zw-coreprod-msk-normalizer-kafka-cluster