kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: smpp-edge
  lifecycle: production
metadata:
  name: messaging-beepsend-simulator
  title: messaging-beepsend-simulator
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Simulator to use for verifying the Beepsend stack in dev and stage. (Will never be released in prod)
apiVersion: backstage.io/v1alpha1