kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: beepsend-api
  lifecycle: production
metadata:
  name: messaging-edge-quantico
  title: messaging-edge-quantico
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 4
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Used to publish data to quantico via Kinesis
apiVersion: backstage.io/v1alpha1