kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: sms-smpp-api
  dependsOn:
    - component:default/messaging-ratequeue-ext2-slave
    - component:default/messaging-ratequeue-ext2-master
  lifecycle: production
metadata:
  name: messaging-accumulator-service-smpp-mt
  tags:
    - sms
  links:
    -
      url: "https://code.hq.twilio.com/messaging/messaging-accumulator-service-smpp-mt-terraform"
      title: IaC Repository
  title: messaging-accumulator-service-smpp-mt
  annotations:
    twilio.com/email: team_sms-customer-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: PNBSD8X
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Service for fragment aggregation and sending the accumulated fragments to the appropriate downstream service (SMPP flow).
apiVersion: backstage.io/v1alpha1