kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: sms-beepsend-insights
  lifecycle: experimental
metadata:
  name: messaging-beepsend-testtool
  tags:
    - sms
  title: messaging-beepsend-testtool
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 4
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Beepsend Test Tool role
apiVersion: backstage.io/v1alpha1