kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: sms-beepsend-inflight
  lifecycle: production
metadata:
  name: messaging-beepsend-ndb-mgmt
  tags:
    - sms
  title: messaging-beepsend-ndb-mgmt
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Beepsend ndb-cluster - mgmt/mysql nodes
apiVersion: backstage.io/v1alpha1