kind: Component
spec:
  type: service
  owner: "group:default/sup_org_zip-810"
  system: mms-edge
  dependsOn:
    - component:default/messaging-ratequeue-mms-master
    - component:default/messaging-ratequeue-mms-slave
    - component:default/nagios-frontend-v2
  lifecycle: production
metadata:
  name: messaging-ratequeue-mms-slave
  tags:
    - mms
  title: messaging-ratequeue-mms-slave
  annotations:
    twilio.com/email: messaging-mms@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P2ECJFE
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PRUJT1W
  description: ratequeue slave for mms
apiVersion: backstage.io/v1alpha1