kind: Component
spec:
  type: service
  owner: "group:default/sup_org_zip-810"
  system: mms-edge
  lifecycle: production
metadata:
  name: mms-gw-proxy-tnx
  tags:
    - mms
  title: mms-gw-proxy-tnx
  annotations:
    twilio.com/email: messaging-mms@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P2ECJFE
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PRUJT1W
  description: mms-gw-proxy for inbound MM7 traffic from tnx
apiVersion: backstage.io/v1alpha1