apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mms-provider
  title: mms-provider
  description: Fake MMS provider
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/mms-provider
    github.com/project-slug: messaging/mms-provider
    pagerduty.com/service-id: P2ECJFE
    twilio.com/email: messaging-mms@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PRUJT1W
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/mms-provider-deploy
  tags:
  - mms
spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-810
  system: mms-edge