kind: Component
spec:
  type: service
  owner: "group:default/sup_org_zip-810"
  system: mms-edge
  lifecycle: production
metadata:
  name: mms-gw
  tags:
    - mms
  links:
    -
      url: "https://github.com/twilio-internal/mms-gw-deploy"
      title: Deployment Repository
  title: mms-gw
  annotations:
    twilio.com/email: messaging-mms@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: true
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P2ECJFE
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PRUJT1W
  description: MMS GW providing MMS service.
apiVersion: backstage.io/v1alpha1