kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: prod-data-shipping-msk-02
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster msk-02 for prod data shipping
apiVersion: backstage.io/v1alpha1