apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smpp-server-normalizer
  title: smpp-server-normalizer
  description: SMPP Server Normalizer Service for ZW Core
  tags:
    - java
  annotations:
    backstage.io/source-location: url:https://github.com/Zipwhip/smpp-server-normalizer
    buildkite.com/project-slug: twilio/zipwhip-smpp-server-normalizer
    github.com/project-slug: zipwhip/smpp-server-normalizer
    github.com/team-slug: zipwhip/developers
    jira/component: smpp-server-normalizer
    jira/project-key: TMINFRA
    pagerduty.com/service-id: PT8ZW7U
    twilio.com/alerting-slack-channel-id-dev: "C04SQD21U9F"
    twilio.com/alerting-slack-channel-id-prod: "C01G6UDFSMV"
    twilio.com/alerting-slack-channel-id-stage: "C05Q8A3DNH3"
    twilio.com/data-classification: restricted
    twilio.com/email: team_zipwhip-core-messaging-engineering@twilio.com
    twilio.com/eu-available: "false"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "true"
    twilio.com/in-scope-sox: "false"
    twilio.com/internet-facing: "false"
    twilio.com/pd-incident-owner-schedule: P2E936R
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/sla-impacting: "true"
    twilio.com/slack-id: "C02H6JYEM7G"
  links:
    - title: Documentation
      url: https://zipwhip.atlassian.net/wiki/spaces/INFRA/pages/644087835/Normalizers
spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-817
  system: zw-core-messaging
  dependsOn:
    - resource:default/core-normalizer
    - resource:default/zw-coreprod-msk-01-kafka-cluster
    - resource:default/zw-coreprod-msk-04-kafka-cluster
    - resource:default/zw-coreprod-msk-normalizer-kafka-cluster
    - resource:default/zw-coreprod-msk-aggregator-kafka-cluster
    - resource:default/zw-coreprod-kafka-cluster
    - resource:default/smpp-server-normalizer-documentdb
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: smpp-server-normalizer-documentdb
  description: DocumentDB database for SMPP server normalizer message processing
  annotations:
    twilio.com/data-classification: restricted
  tags:
    - database
    - documentdb
    - docdb-cluster-docdb-01
spec:
  type: database
  owner: group:default/sup_org_zip-817
  system: zw-core-messaging
  dependencyOf:
    - component:default/smpp-server-normalizer