kind: Component
spec:
  type: service
  owner: jm-sup-org-34
  system: smpp-edge
  dependsOn:
    - component:default/eventbus
    - component:default/sms-dlr-ack-gateway
    - component:default/sms-event-platform
    - component:default/carrierops-provider-service
    - component:default/messaging-incoming-gateway
  lifecycle: production
metadata:
  name: smpp-provider-edge
  links:
    -
      url: "https://github.com/twilio-internal/smpp-provider-edge-deploy"
      title: Deployment Repository
  title: smpp-provider-edge
  annotations:
    twilio.com/email: sms-edge@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 0
    pagerduty.com/service-id: P69YK74
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PZV0VW5
  description: Twilio SMS Gateway facilitating connectivity to Short Message Service Centers
apiVersion: backstage.io/v1alpha1