apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sms-smpp-api-customer-simulator
  title: sms-smpp-api-customer-simulator
  description: SMPP API Customer Simulator
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/sms/sms-smpp-api-customer-simulator
    github.com/project-slug: sms/sms-smpp-api-customer-simulator
    pagerduty.com/service-id: PNBSD8X
    twilio.com/email: team_sms-customer-edge@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PZV0VW5
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
  links: []
  tags:
  - sms
spec:
  type: service
  lifecycle: experimental
  owner: jm-sup-org-34
  system: sms-smpp-api