apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sms-smpp-api-proxy
  title: sms-smpp-api-proxy
  description: SMPP API Proxy
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/sms/sms-smpp-api-proxy
    github.com/project-slug: sms/sms-smpp-api-proxy
    pagerduty.com/service-id: PNBSD8X
    twilio.com/email: team_sms-customer-edge@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PZV0VW5
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '0'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/sms-smpp-api-proxy-deploy
  tags:
  - sms
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-34
  system: sms-smpp-api