kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster for various services (spam-filter/carrier-lookup/smpp-gateway/...)
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-msk-01-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster msk-01
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-msk-03-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster msk-03
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-msk-04-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster msk-04
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-msk-aggregator-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster for aggregator workloads
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup_org_zip-817"
  system: zw-core-messaging
metadata:
  name: zw-coreprod-msk-normalizer-kafka-cluster
  tags:
    - kafka
    - msk
  annotations:
    twilio.com/data-classification: restricted
  description: MSK Kafka cluster for normalizer
apiVersion: backstage.io/v1alpha1