apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zw-twlo-edge-gateway
  title: zw-twlo-edge-gateway
  description: Zipwhip/Twilio Edge Gateway for ZW Core
  tags:
    - java
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/zw-twlo-edge-gateway
    buildkite.com/project-slug: twilio/zipwhip-zw-twlo-edge-gateway
    github.com/project-slug: twilio-internal/zw-twlo-edge-gateway
    github.com/team-slug: twilio/messaging
    jira/component: zw-twlo-edge-gateway
    jira/project-key: TMINFRA
    pagerduty.com/service-id: PT8ZW7U
    twilio.com/alerting-slack-channel-id-dev: "C04SQD21U9F"
    twilio.com/alerting-slack-channel-id-prod: "C01G6UDFSMV"
    twilio.com/alerting-slack-channel-id-stage: "C05Q8A3DNH3"
    twilio.com/data-classification: restricted
    twilio.com/email: team_zipwhip-core-messaging-engineering@twilio.com
    twilio.com/eu-available: "false"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "true"
    twilio.com/in-scope-sox: "false"
    twilio.com/internet-facing: "false"
    twilio.com/pd-incident-owner-schedule: P2E936R
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/sla-impacting: "true"
    twilio.com/slack-id: "C02H6JYEM7G"
  links:
    - title: Alarms/Documentation
      url: https://twilio-productivity.atlassian.net/wiki/spaces/MSG/pages/527532837/ZW+Twilio+Edge+Gateway+Alarms
    - title: Failure Modes
      url: https://twilio-productivity.atlassian.net/wiki/spaces/MSG/pages/701470202/Edge+Gateway+Failure+Modes
    - title: Grafana Dashboard
      url: https://g-870ae6cc62.grafana-workspace.us-west-2.amazonaws.com/d/be0io09j23chsa/zw-twilio-edge-gateway?orgId=1

spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-817
  system: zw-core-messaging
  dependsOn:
    - resource:default/zw-coreprod-msk-01-kafka-cluster
    - resource:default/zw-coreprod-msk-03-kafka-cluster
    - resource:default/zw-coreprod-kafka-cluster