apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Pantalasa frontend service
spec:
  type: frontend
  lifecycle: production
  owner: eng-team
  system: public-websites
