apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alert-config-api
  title: alert-config-api
  description: 'Store and query alert configs '
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/data/meerkat-api
    github.com/project-slug: data/meerkat-api
    pagerduty.com/service-id: P729B1J
    twilio.com/email: data-reportcenter@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P8O7PRY
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2398
  system: enterprise-insights
  dependsOn:
  - component:default/eventbus
  - component:default/eventbus
  - component:default/ud-entity-schema-api
  - component:default/report-center-orchestrator
  - component:default/accounts-api
  - component:default/accounts-api
  - component:default/audit-events-api