apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: audit-events-processor
  title: audit-events-processor
  description: Validates incoming Audit Events sent to SQS and stores to DynamoDB
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/audit-events-processor
    github.com/project-slug: twilio/audit-events-processor
    pagerduty.com/service-id: P729B1J
    twilio.com/email: data-reportcenter@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P8O7PRY
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2398
  system: audit-events-api-processor
  dependsOn:
  - component:default/accounts-api
  - component:default/audit-events-api
  - component:default/eventbus
  - component:default/eventbus
  - component:default/feature-service
  - component:default/ud-entity-schema-api