apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: audit-events-mirror
  title: audit-events-mirror
  description: Mirrors Audit Events from one region to another region
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/data/audit-events-mirror
    github.com/project-slug: data/audit-events-mirror
    pagerduty.com/service-id: P729B1J
    twilio.com/email: data-reportcenter@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P8O7PRY
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2398
  system: audit-events-api-processor