apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cde-feature-store-customer-traffic-profile
  title: cde-feature-store-customer-traffic-profile
  description: Pipeline to manage feature groups specific to traffic profile
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/cde-feature-store-customer-traffic-profile
    github.com/project-slug: messaging/cde-feature-store-customer-traffic-profile
    pagerduty.com/service-id: PAC7IAC
    twilio.com/email: team_messaging-customer-growth@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P883LB8
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-2040
  system: intelligent-recommendations