kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2398"
  system: enterprise-insights
  dependsOn:
    - component:default/report-center-orchestrator
    - component:default/report-center-data-engine
    - component:default/eventbus
    - component:default/eventbus
    - component:default/ud-entity-schema-api
  lifecycle: production
metadata:
  name: debug-events-alerter
  title: debug-events-alerter
  annotations:
    twilio.com/email: data-reportcenter@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: P729B1J
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: P8O7PRY
  description: Alerter streaming app for debug events 
apiVersion: backstage.io/v1alpha1