apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intelligence-configuration-manager
  title: intelligence-configuration-manager
  description: Role for managing notification configurations for Intelligent Alert
    customers
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/intelligence-configuration-manager
    github.com/project-slug: messaging/intelligence-configuration-manager
    pagerduty.com/service-id: PHUUA1R
    twilio.com/email: messaging-intelligence@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PWS471W
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/intelligence-configuration-manager-deploy
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1381
  system: online-learning-pipelines
  dependsOn:
  - component:default/accounts-api
  - component:default/debugger-data-service