kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1381"
  system: online-learning-pipelines
  dependsOn:
    - component:default/eventbus
    - component:default/ud-entity-schema-api
  lifecycle: experimental
metadata:
  name: intelligence-inference-worker-shadow
  title: intelligence-inference-worker-shadow
  annotations:
    twilio.com/email: messaging-intelligence@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PHUUA1R
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PWS471W
  description: ML inference service for detecting messaging traffic anomalies (shadow testing)
apiVersion: backstage.io/v1alpha1