apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intelligence-recommendations-service
  title: intelligence-recommendations-service
  description: Intelligence Recommendations is a service that provides solution recommendations
    to customers messaging issues based on the problem and root cause
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/intelligence-recommendations-service
    github.com/project-slug: messaging/intelligence-recommendations-service
    pagerduty.com/service-id: PHUUA1R
    twilio.com/email: messaging-intelligence@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PWS471W
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/intelligence-recommendations-service-deploy
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1381
  system: intelligent-recommendations