apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intelligence-load-tester
  title: intelligence-load-tester
  description: Generate configurable loads for intelligence alerts pipeline
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/intelligence-load-tester
    github.com/project-slug: messaging/intelligence-load-tester
    pagerduty.com/service-id: PHUUA1R
    twilio.com/email: messaging-intelligence@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PWS471W
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1381
  system: online-learning-pipelines