apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intelligence-recommendations-service-e2e-tests
  title: intelligence-recommendations-service-e2e-tests
  description: E2E tests for intelligence-recommendations-service
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/intelligence-recommendations-service-e2e-tests
    buildkite.com/project-slug: twilio/twilio-internal-intelligence-recommendations-service-e2e-tests
    github.com/project-slug: twilio-internal/intelligence-recommendations-service-e2e-tests
    jira/project-key: MSGINTELLI-1425
    pagerduty.com/service-id: PHUUA1R
    twilio.com/email: team_messaging-intelligence@twilio.com
    twilio.com/ldap-group: team_messaging-intelligence
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: messaging-intelligence-ics
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/intelligence-recommendations-service-e2e-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-intelligence-recommendations-service-e2e-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/intelligence-recommendations-service-e2e-tests-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1381
  system: intelligent-recommendations