apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intelligent-alerts-api
  title: intelligent-alerts-api
  description: Repository created by Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/intelligent-alerts-api
    buildkite.com/project-slug: twilio/twilio-internal-intelligent-alerts-api
    github.com/project-slug: twilio-internal/intelligent-alerts-api
    jira/project-key: MSGINTELLI-1936
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_messaging-intelligence@twilio.com
    twilio.com/ldap-group: team_messaging-intelligence
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: messaging-intelligence-ics
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/intelligent-alerts-api-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-intelligent-alerts-api
  - title: IaC Repository
    url: https://github.com/twilio-internal/intelligent-alerts-api-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1381
  system: online-learning-pipelines