kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2398"
  system: enterprise-insights
  dependsOn:
    - component:default/report-center-orchestrator
    - component:default/report-center-data-engine
    - component:default/eventbus
    - component:default/ud-entity-schema-api
    - component:default/accounts-api
    - component:default/id-account-manager-service
    - component:default/pied-piper-ingest
  lifecycle: production
metadata:
  name: report-center-tester
  title: report-center-tester
  annotations:
    twilio.com/email: data-reportcenter@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: P729B1J
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P8O7PRY
  description: Used for all kinds of testing such as cluster testing, scalability testing, failure testing etc,  of report center platform
apiVersion: backstage.io/v1alpha1