kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1381"
  system: zipwhip-data-warehouse-systems
  lifecycle: production
metadata:
  name: zipwhip-rbi-exports-01
  title: zipwhip-rbi-exports-01
  annotations:
    twilio.com/email: team_messaging-insights@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PBFDZ8P
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PWS471W
  description: Server producing exports for zipwhip EOL customers
apiVersion: backstage.io/v1alpha1