kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2448"
  system: "system:default/execution-management-service"
  dependsOn:
    - resource:twilio/github-repo-91071
    - resource:twilio/github-repo-91228
    - resource:twilio/github-repo-91239
    - resource:twilio/github-repo-91890
    - resource:twilio-internal/github-repo-840018190
    - resource:twilio-internal/github-repo-840018207
    - component:default/messaging-ratequeue-apps-master
    - component:default/messaging-ratequeue-apps-slave
    - component:default/messaging-state-service
    - component:default/messaging-feedback-service
    - component:default/accounts-api
  lifecycle: production
  providesApis:
    - api:channelorch-ems-api
metadata:
  name: channelorch-ems-api
  links:
    -
      url: "https://twilio-productivity.atlassian.net/wiki/spaces/MSG/pages/443812769/Channel+Orchestration+-+Execution+Management+Service+EMS"
      title: Documentation
    -
      url: "https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/756155087/channelorch-ems-api"
      title: Runbook
    -
      url: "https://app.datadoghq.com/dashboard/mr2-ycw-xhs/omnichannel-interface-messaging-msg-send?fromUser=false&overl"
      title: Datadog Dashboard
  title: channelorch-ems-api
  namespace: default
  annotations:
    snyk.io/org-id: 3879ec5f-48d8-45f3-b847-6a4db933a659
    snyk.io/targets: twilio/channelorch-ems-api
    jira/project-key: MSGOI
    twilio.com/email: team_omnichannel-interface@twilio.com
    github.com/project-slug: twilio/channelorch-ems-api
    twilio.com/eu-available: false
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: false
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: PBNVJ5Y
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: false
    twilio.com/security-tier: 1
    twilio.com/sla-impacting: true
    twilio.com/in-scope-hipaa: true
    twilio.com/internet-facing: false
    twilio.com/data-classification: confidential
    twilio.com/alerting-slack-channel-id-dev: C04EZFUGRTK
    twilio.com/alerting-slack-channel-id-prod: C04E6A7TYMD
    twilio.com/alerting-slack-channel-id-stage: C04ELP5DJCB
  description: This service addresses the channel orchestration for RCS/Fallback, storing channel attempt relationships and state management
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: database
  owner: "group:default/sup-org-2448"
  system: "system:default/execution-management-service"
  dependencyOf:
    - component:default/channelorch-ems-api
metadata:
  name: channelorch.ems
  tags:
    - dynamodb
  description: DynamoDB table for execution plans in channel orchestration EMS
apiVersion: backstage.io/v1alpha1
---
kind: Resource
spec:
  type: queue
  owner: "group:default/sup-org-2448"
  system: "system:default/execution-management-service"
  dependencyOf:
    - component:default/channelorch-ems-api
    - component:default/messaging-service-event-handler
metadata:
  name: channelorch-ems-failed-status-updates
  tags:
    - sqs
  description: SQS queue for EMS DLQ
apiVersion: backstage.io/v1alpha1
---
kind: API
spec:
  type: openapi
  owner: "group:sup-org-1714"
  system: msg-send
  lifecycle: production
  definition:
    $text: "https://code.hq.twilio.com/twilio/channelorch-ems-api/blob/main/docs/openapi/channelorch_ems_api.yaml"
metadata:
  name: channelorch-ems-api
  description: API spec for messaging-msg-send
apiVersion: backstage.io/v1alpha1