apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-app-dequeue
  title: messaging-app-dequeue
  description: Message Dequeuer for Messaging App Platform
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/app-dequeue
    github.com/project-slug: messaging/app-dequeue
    pagerduty.com/service-id: P6ZTYC7
    twilio.com/email: messaging-services@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PEPHN4O
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-app-dequeue-deploy
  - title: IaC Repository
    url: https://github.com/twilio-internal/messaging-app-dequeue-terraform
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382764380/messaging-number-pool-service
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-168
  system: messaging-services-core
  dependsOn:
  - component:default/messaging-service-orchestrator
  - component:default/message-state-service
  - component:default/messaging-ratequeue-apps-master
  - component:default/messaging-ratequeue-apps-slave
  - component:default/accounts-api
  - component:default/contentstore
  - component:default/eventbus
  - component:default/feature-service
  - component:default/messaging-inflight-service
  - component:default/messaging-number-pool-service
  - component:default/messaging-opt-out-service
  - component:default/messaging-msg-send
  - component:default/messaging-blacklist-service
  - component:default/messaging-service-configuration
  - component:default/channelorch-ems-api
  - component:default/channel-intelligence-api