apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-service-orchestrator
  title: messaging-service-orchestrator
  description: The service responsible for add-on invocation and execution as well
    as acting as a messaging service gateway in the future
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/messaging-service-orchestrator
    github.com/project-slug: messaging/messaging-service-orchestrator
    pagerduty.com/service-id: P6ZTYC7
    twilio.com/email: messaging-services@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PEPHN4O
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-service-orchestrator-deploy
  - title: IaC Repository
    url: https://github.com/twilio-internal/messaging-service-orchestrator-terraform
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382773943/messaging-service-orchestrator
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-168
  system: messaging-services-packages
  dependsOn:
  - component:default/feature-service
  - component:default/tbt-url-shortener
  - component:default/messaging-service-configuration
  - component:default/messaging-template-translation