apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-number-pool-service
  title: messaging-number-pool-service
  description: Number Pool Service for App Platform
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/number-pool-service
    github.com/project-slug: messaging/number-pool-service
    pagerduty.com/service-id: P6ZTYC7
    twilio.com/email: messaging-services@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PEPHN4O
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-number-pool-service-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382764382/messaging-app-dequeue
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-168
  system: messaging-services-core
  dependsOn:
  - component:default/messaging-sticky-sender-service
  - component:default/number-validation-service
  - component:default/accounts-api
  - component:default/feature-service
  - component:default/eventbus
  - component:default/data-producer-api
  - component:default/dip
  - component:default/messaging-routing-service
  - component:default/ud-entity-schema-api
  - component:default/messaging-service-configuration
  - component:default/messaging-ott-rbm-outbound
  - component:default/messaging-ott-management-api
  - component:default/messaging-ott-storehouse
  - component:default/audit-events-api