apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-service-configuration
  title: messaging-service-configuration
  description: 'Role to manage messaging application related configuration including number pool management'
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/messaging-service-configuration
    github.com/project-slug: messaging/messaging-service-configuration
    pagerduty.com/service-id: P6ZTYC7
    twilio.com/email: messaging-services@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PEPHN4O
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-service-configuration-deploy
  - title: IaC Repository
    url: https://code.hq.twilio.com/messaging/messaging-service-configuration-terraform
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382769019/messaging-service-configuration
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-168
  system: messaging-services-core
  dependsOn:
  - component:default/messaging-a2p-registrations-api
  - component:default/number-validation-service
  - component:default/messaging-number-pool-service
  - component:default/yellow-pages
  - component:default/sender-id-service
  - component:default/messaging-a2p-api
  - component:default/inventory-caching-service
  - component:default/inventory-federation-service
  - component:default/accounts-api
  - component:default/data-producer-api
  - component:default/eventbus
  - component:default/feature-service
  - component:default/tx-data-api
  - component:default/ud-entity-schema-api
  - component:default/messaging-ott-storehouse
  - component:default/audit-events-api
  - component:default/gradual-rollout