apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-sticky-sender-service
  title: messaging-sticky-sender-service
  description: messaging-sticky-sender-service
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/sticky-sender-service
    github.com/project-slug: messaging/sticky-sender-service
    pagerduty.com/service-id: P6ZTYC7
    twilio.com/email: messaging-services@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PEPHN4O
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-sticky-sender-service-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382779213/messaging-sticky-sender-service
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-168
  system: messaging-services-core