kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2448"
  system: "system:default/msg-send"
  dependsOn:
    - resource:messaging/github-repo-28506
  lifecycle: experimental
metadata:
  name: omnichannel-interface-load-tester
  title: omnichannel-interface-load-tester
  annotations:
    jira/project-key: MSGOI
    twilio.com/email: team_omnichannel-interface@twilio.com
    twilio.com/eu-available: false
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: false
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: P95VOIP
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: false
    twilio.com/security-tier: 2
    twilio.com/sla-impacting: false
    twilio.com/in-scope-hipaa: false
    twilio.com/internet-facing: false
    twilio.com/data-classification: confidential
    twilio.com/pd-incident-owner-schedule: P99UI2Y
    twilio.com/alerting-slack-channel-id-dev: C04EZFUGRTK
    twilio.com/alerting-slack-channel-id-prod: C04E6A7TYMD
    twilio.com/alerting-slack-channel-id-stage: C04ELP5DJCB
  description: Load generator role for omnichannel interface team
apiVersion: backstage.io/v1alpha1