apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alert-enrichment-service
  title: alert-enrichment-service
  description: Enriches detected route degradations with additional information to
    forward to SNES and SNOC engineers
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/alert-enrichment-service
    github.com/project-slug: super-network/alert-enrichment-service
    pagerduty.com/service-id: PBLO97C
    buildkite.com/project-slug: twilio/super-network-alert-enrichment-service
    jira/project-key: SNM
    twilio.com/email: super-network-monitoring@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '2'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/alert-enrichment-service-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-579
  system: super-network-insights-core
  dependsOn:
  - component:default/supernetwork-emergency-service
  - component:default/supernetwork-insights-mapping-service
  - component:default/carrierops-provider-service
  - component:default/data-producer-api
  - component:default/network-registry