apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: library
  lifecycle: production
  owner: sup-org-579
  system: sms-traffic-aggregator
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "3"
    twilio.com/email: team_super-network-health@twilio.com
    twilio.com/slack-channel-name: "#eng-snh-stage-alerts"
    backstage.io/techdocs-ref: url:https://code.hq.twilio.com/super-network/base-spark-app/blob/main/README.md
    github.com/project-slug: super-network/base-spark-app
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/base-spark-app
  name: base-spark-app
  title: base-spark-app
  description: "SN Health Base docker image for spark applications"