apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: broken-routes
  title: broken-routes
  description: Broken routes provider
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/broken-routes
    github.com/project-slug: super-network/broken-routes
    buildkite.com/project-slug: twilio/super-network-broken-routes
    jira/project-key: SNH
    pagerduty.com/service-id: P8XXSPT
    twilio.com/email: super-health@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '2'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-579
  system: super-network-emergency-systems