kind: Component
spec:
  type: service
  owner: jm-sup-org-162
  system: provider-service
  lifecycle: experimental
metadata:
  name: carrierops-provider-service-load-tester
  title: carrierops-provider-service-load-tester
  annotations:
    twilio.com/email: team_messaging-sit@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: P5E0NDN
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P9MX5KH
  description: Load tester role for provider service
apiVersion: backstage.io/v1alpha1