apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carrierops-provider-service-e2e-tests
  title: carrierops-provider-service-e2e-tests
  description: Provider service e2e (cluster) test application
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/carrierops-provider-service-e2e-tests
    buildkite.com/project-slug: twilio/twilio-internal-carrierops-provider-service-e2e-tests
    github.com/project-slug: twilio-internal/carrierops-provider-service-e2e-tests
    jira/project-key: SREG
    pagerduty.com/service-id: P8XXSPT
    twilio.com/email: team_messaging-sit@twilio.com
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-msit-alerts
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/carrierops-provider-service-e2e-tests-deploy
  - title: Buildkite Pipeline
    url: https://buildkite.com/twilio/provider-service-otk-cluster-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/carrierops-provider-service-e2e-tests-iac
         
spec:
  type: service
  lifecycle: experimental
  owner: jm-sup-org-162
  system: provider-service