apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: library
  lifecycle: production
  owner: sup-org-579
  system: super-network-emergency-systems
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "3"
    twilio.com/email: team_super-network-health@twilio.com
    twilio.com/slack-channel-name: "#eng-snh-stage-alerts"
    backstage.io/techdocs-ref: url:hhttps://code.hq.twilio.com/super-network/dogtray/blob/master/README.md
    github.com/project-slug: super-network/dogtray
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/dogtray
  name: dogtray
  title: dogtray
  description: "Helper library for publishing http client and server metrics to datadog"