apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-volumes-aggregator
  title: messaging-volumes-aggregator
  description: MDP Spark app for volumes aggregations
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/mdp-spark-volumes-aggregator
    github.com/project-slug: carrierops/messaging-volumes-aggregator
    twilio.com/github-server: code.hq.twilio.com
    buildkite.com/project-slug: twilio/carrierops-messaging-volumes-aggregator
    jira/project-key: SNCE
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 6113f470-8c3e-4df4-ad76-1857abc5e131
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '3'
    pagerduty.com/service-id: PESCFOL
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/email: super-cost@twilio.com
    twilio.com/slack-channel-name: "#help-sn-cost"
  links:
    - title: Runbook
      url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382778018/messaging-volumes-aggregator+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: rate-manager
  dependsOn:
  - component:default/snce-provider-cost-api