apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-reporting-rates
  title: messaging-reporting-rates
  description: Messaging Reporting Rates
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/messaging-reporting-rates
    github.com/project-slug: carrierops/messaging-reporting-rates
    twilio.com/github-server: code.hq.twilio.com
    buildkite.com/project-slug: twilio/carrierops-messaging-reporting-rates
    jira/project-key: SNCE
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 0397e3ee-1bf4-4607-b067-1e63142e46fc
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    pagerduty.com/service-id: PESCFOL
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/email: super-cost@twilio.com
    twilio.com/slack-channel-name: "#help-sn-cost"  
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-reporting-rates-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382777440/messaging-reporting-rates+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: rate-manager
  dependsOn:
  - component:default/eventbus
  - component:default/snce-provider-cost-api
  - component:default/ud-entity-schema-api