kind: Component
spec:
  type: service
  owner: jm-sup-org-162
  system: supplier-engagement
  lifecycle: experimental
metadata:
  name: msit-load-tester
  title: msit-load-tester
  annotations:
    twilio.com/email: team_messaging-sit@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: P5E0NDN
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P9MX5KH
  description: The msit-load-tester role is specific to executing the load tests for MSIT team
apiVersion: backstage.io/v1alpha1