apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: network-registry
  title: network-registry
  description: Network Registry is responsible for Networks and NetworkAccessProfile
    resources
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/network-registry
    github.com/project-slug: messaging/network-registry
    pagerduty.com/service-id: PESCFOL
    twilio.com/email: super-cost@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: network-registry