apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: opportunity-registry
  title: opportunity-registry
  description: Opportunity registry is the source of truth for the messaging routing opportunity management which is a Twilio-initiated process of getting more competitive routing offerings from 
    suppliers.
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/opportunity-registry
    buildkite.com/project-slug: twilio/twilio-internal-opportunity-registry
    github.com/project-slug: twilio-internal/opportunity-registry
    jira/project-key: MSIT
    pagerduty.com/service-id: P5E0NDN
    snyk.io/org-id: a83a108e-04cf-424a-a96c-898ce5bf2118
    snyk.io/project-ids: fcb72233-00da-47fe-98f9-20b444fb05b3
    twilio.com/email: team_messaging-supply-insights-trust@twilio.com
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "2"
    twilio.com/slack-channel-name: "#eng-msit"
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/opportunity-registry-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-opportunity-registry
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/opportunity-registry-iac
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/980353030
spec:
  type: service
  lifecycle: production
  owner: sup-org-682
  system: supplier-engagement
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: opportunity-registry-api
  description: "API for managing messaging routing opportunities"
  tags:
  - supply-management
  - opportunity-registry-api
spec:
  providesApis:
  - opportunity-registry-api
  type: openapi
  lifecycle: production
  owner: sup-org-682
  system: supplier-engagement
  definition:
    $text: https://github.com/twilio-internal/opportunity-registry/blob/1a73766ead2342628222a0adc45becf0646f20b3/opportunity-registry-protocol/src/main/openapi/opportunity-registry.oas3.yaml