apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provider-service-data-export
  title: provider-service-data-export
  description: aggregate provider data export to s3
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/provider-service-data-export
    buildkite.com/project-slug: twilio/twilio-internal-provider-service-data-export
    github.com/project-slug: twilio-internal/provider-service-data-export
    jira/project-key: MSIT
    pagerduty.com/service-id: P9MX5KH
    twilio.com/email: team_messaging-supply-insights-trust@twilio.com
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '2'
    twilio.com/slack-channel-name: eng-msit
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/provider-service-data-export-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-provider-service-data-export
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/provider-service-data-export-iac
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-162
  system: supplier-engagement