apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provider-service-data-consumer
  title: provider-service-data-consumer
  description: Sample app to demonstrate usage of supplier configuration data
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/provider-service-data-consumer
    buildkite.com/project-slug: twilio/twilio-internal-provider-service-data-consumer
    github.com/project-slug: twilio-internal/provider-service-data-consumer
    jira/project-key: SREG
    pagerduty.com/service-id: P8XXSPT
    twilio.com/email: team_messaging-supply-insights-trust@twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-msit
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/provider-service-data-consumer-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-provider-service-data-consumer
  - title: IaC Repository
    url: https://github.com/twilio-internal/provider-service-data-consumer-iac
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-162
  system: provider-service