apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ratedeck-converter-validator
  title: ratedeck-converter-validator
  description: "Service for validating ratedeck conversion "
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/ratedeck-converter-validator
    buildkite.com/project-slug: twilio/carrierops-ratedeck-converter-validator
    github.com/project-slug: carrierops/ratedeck-converter-validator
    jira/project-key: SNCE
    pagerduty.com/service-id: PESCFOL
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 2632d899-0f1f-4b29-91e3-9237f36fbdfc
    twilio.com/email: super-cost@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "5"
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/ratedeck-converter-validator-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: rate-ingestion
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ratedeck-converter-validator-api
  description: "Ratedeck Conversion Validator API"
  tags:
  - supply-management
  - ratedeck-converter-validator-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-682
  system: rate-ingestion
  definition:
    $text: https://code.hq.twilio.com/carrierops/ratedeck-converter-validator/blob/main/docs/spec/api.yaml