apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: route-registry-lighthouse-e2e-otk-tests
  title: route-registry-lighthouse-e2e-otk-tests
  description: Route Registry and Lighthouse e2e tests
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/route-registry-lighthouse-e2e-otk-tests
    buildkite.com/project-slug: twilio/twilio-internal-route-registry-lighthouse-e2e-otk-tests
    github.com/project-slug: twilio-internal/route-registry-lighthouse-e2e-otk-tests
    jira/project-key: SNCE
    pagerduty.com/service-id: TBD
    twilio.com/email: team_super-network-cost-engineering@twilio.com
    twilio.com/ldap-group: team_super-network-cost-engineering
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: help-sn-cost
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/route-registry-lighthouse-e2e-otk-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-route-registry-lighthouse-e2e-otk-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/route-registry-lighthouse-e2e-otk-tests-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-682
  system: route-registry