apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sms-synthetic-testing-feedback
  title: sms-synthetic-testing-feedback
  description: Service for reporting feedback on sms synthetic testing
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/sms-synthetic-testing-feedback
    buildkite.com/project-slug: twilio/carrierops-sms-synthetic-testing-feedback
    github.com/project-slug: carrierops/sms-synthetic-testing-feedback
    jira/project-key: SNCE
    pagerduty.com/service-id: PESCFOL
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 246ab188-96ba-46f6-971c-ab7537ac461d
    twilio.com/email: super-cost@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-channel-name: "#help-sn-cost"
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/sms-synthetic-testing-feedback-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382780345/sms-synthetic-testing-feedback+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: synthetic-testing-service
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus
  - component:default/sms-capabilities-evaluator
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sms-synthetic-testing-feedback-api
  description: "API for submitting feedback for synthetic testing"
  tags:
  - supply-management
  - sms-synthetic-testing-feedback-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-682
  system: synthetic-testing-service
  definition:
    $text: https://code.hq.twilio.com/carrierops/sms-synthetic-testing-feedback/blob/main/api/src/main/resources/sms-synthetic-testing-feedback.yaml