kind: Component
spec:
  type: service
  owner: "group:default/sup-org-682"
  system: synthetic-testing-service
  lifecycle: experimental
metadata:
  name: sms-capabilities-evaluator-performance-tester
  title: sms-capabilities-evaluator-performance-tester
  annotations:
    twilio.com/email: super-cost@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 5
    pagerduty.com/service-id: PESCFOL
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P9MX5KH
  description: Performance testing role for running tests on sms-capabilities-evaluator via TAF
apiVersion: backstage.io/v1alpha1