apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snce-state-updater
  title: snce-state-updater
  description: Supernetwork Cost Management V2 rates state updater service
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/snce-state-updater
    github.com/project-slug: carrierops/snce-state-updater
    twilio.com/github-server: code.hq.twilio.com
    jira/project-key: SNCE
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 7c411ea3-54e3-4e10-a18a-49363e28e536
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '3'
    pagerduty.com/service-id: PESCFOL
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/email: super-cost@twilio.com
    twilio.com/slack-channel-name: "#help-sn-cost"
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/snce-state-updater-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382776264/snce-state-updater+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: rate-manager
  dependsOn:
  - component:default/eventbus
  - component:default/ud-entity-schema-api