apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snce-cost-alerting
  title: snce-cost-alerting
  description: Service for checking new sms costs, comparing them with current ones
    and alerting if there's an increase
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/snce-cost-alerting
    github.com/project-slug: carrierops/snce-cost-alerting
    twilio.com/github-server: code.hq.twilio.com
    buildkite.com/project-slug: twilio/carrierops-snce-cost-alerting
    jira/project-key: SNCE
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: 173e2560-675d-48fa-88be-a008bc9fa95e
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '3'
    pagerduty.com/service-id: PESCFOL
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/email: super-cost@twilio.com
    twilio.com/slack-channel-name: "#help-sn-cost"
  links:
    - title: Runbook
      url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382770516/snce-cost-alerting+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: cost-monitoring
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus
  - component:default/snce-provider-cost-api
  - component:default/carrierops-provider-service