apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snce-state-calculator
  title: snce-state-calculator
  description: Rates State Calculator
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/carrierops/snce-state-calculator
    buildkite.com/project-slug: twilio/carrierops-snce-state-calculator
    github.com/project-slug: carrierops/snce-state-calculator
    jira/project-key: SNCE
    pagerduty.com/service-id: PESCFOL
    snyk.io/org-id: ccd9f4a3-9bb3-48c3-a25b-2da4db09a45a
    snyk.io/project-id: e4114481-8e31-471d-9f4a-042edbc09714
    twilio.com/email: super-cost@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "3"
    twilio.com/slack-channel-name: "#help-sn-cost"
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/snce-state-calculator-deploy
  - title: Runbook
    url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382776283/snce-state-calculator+runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: rate-manager
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus
  - component:default/snce-provider-cost-api
  - component:default/network-registry
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: snce-state-calculator-api
  description: "API for State calculator tasks"
  tags:
  - supply-management
  - snce-state-calculator-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-682
  system: rate-manager
  definition:
    $text: https://code.hq.twilio.com/carrierops/snce-state-calculator/blob/main/docs/spec/api.yaml