apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snh-terraform
  title: snh-terraform
  description: Synchronizes monitors defined in VCS to Datadog using Terraform
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/snh-terraform
    github.com/project-slug: super-network/snh-terraform
    pagerduty.com/service-id: PBLO97C
    twilio.com/email: super-network-monitoring@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-579
  system: super-network-insights-core