apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supernetwork-insights-inflight-messaging
  title: supernetwork-insights-inflight-messaging
  description: Spark application generating SMS inbound Datadog metrics
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/super-network/supernetwork-insights-inflight-messaging
    github.com/project-slug: super-network/supernetwork-insights-inflight-messaging
    pagerduty.com/service-id: PBLO97C
    twilio.com/email: super-network-monitoring@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P9MX5KH
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '2'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-579
  system: metrics-generation
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus
  - component:default/supernetwork-insights-mapping-service
  - component:default/carrierops-provider-service
  - component:default/datapooch
  - component:default/benchmark-api