apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supplier-feedback-e2e-otk-tests
  title: supplier-feedback-e2e-otk-tests
  description: Repository created by Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/supplier-feedback-e2e-otk-tests
    buildkite.com/project-slug: twilio/twilio-internal-supplier-feedback-e2e-otk-tests
    github.com/project-slug: twilio-internal/supplier-feedback-e2e-otk-tests
    jira/project-key: MSIT
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_messaging-supply-insights-trust@twilio.com
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '2'
    twilio.com/slack-channel-name: replace-me
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/supplier-feedback-e2e-otk-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-supplier-feedback-e2e-otk-tests
spec:
  type: service
  lifecycle: experimental
  owner: jm-sup-org-162
  system: system:default/supplier-engagement