apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supplier-registry-reader
  title: supplier-registry-reader
  description: Read-only api for getting supplier configuration data
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/supplier-registry-reader
    buildkite.com/project-slug: twilio/twilio-internal-supplier-registry-reader
    github.com/project-slug: twilio-internal/supplier-registry-reader
    jira/project-key: MSIT
    pagerduty.com/service-id: P9MX5KH
    snyk.io/org-id: a83a108e-04cf-424a-a96c-898ce5bf2118
    snyk.io/project-id: a2c33577-cce8-480d-84b5-9381ab068687
    twilio.com/email: team_messaging-supply-insights-trust@twilio.com
    twilio.com/ldap-group: team_messaging-supply-insights-trust
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "2"
    twilio.com/slack-channel-name: eng-msit
    twilio.com/in-scope-sox: "false"
    twilio.com/data-classification: "restricted"
    twilio.com/internet-facing: "false"
    twilio.com/eu-available: "true"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "true"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "false"
    twilio.com/sla-impacting: "false"

  links:
    - title: Deployment Repository
      url: https://www.github.com/twilio-internal/supplier-registry-reader-deploy
    - title: Buildkite Pipeline
      url: https://www.buildkite.com/twilio/twilio-internal-supplier-registry-reader
    - title: IaC Repository
      url: https://github.com/twilio-internal/supplier-registry-reader-iac
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-682
  system: provider-service

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: supplier-registry-reader-api
  description: "Providers Service API"
  tags:
    - supply-management
    - supplier-registry-reader-api
spec:
  providesAPIs:
    - supplier-registry-reader-api
  type: openapi
  lifecycle: experimental
  owner: group:default/sup-org-682
  system: provider-service
  definition:
    $text: https://github.com/twilio-internal/supplier-registry-reader/blob/main/server/src/main/resources/openapi/openapi-spec-v3.yaml