apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cde-ds-mdr-generator
  title: cde-ds-mdr-generator
  description: CDE deliverability score MDR generator for cluster tests
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/cde-ds-mdr-generator
    buildkite.com/project-slug: twilio/twilio-internal-cde-ds-mdr-generator
    github.com/project-slug: twilio-internal/cde-ds-mdr-generator
    jira/project-key: MCG
    pagerduty.com/service-id: PAC7IAC
    twilio.com/email: team_messaging-customer-growth@twilio.com
    twilio.com/ldap-group: team_messaging-customer-growth
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: eng-messaging-customer-growth
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/cde-ds-mdr-generator-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-cde-ds-mdr-generator
  - title: IaC Repository
    url: https://github.com/twilio-internal/cde-ds-mdr-generator-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-2040
  system: deliverability-score