apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: communication-logs-e2e-tests
  title: communication-logs-e2e-tests
  description: E2E Cluster Tests for messaging logs API
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/communication-logs-e2e-tests
    buildkite.com/project-slug: twilio/twilio-internal-communication-logs-e2e-tests
    github.com/project-slug: twilio-internal/communication-logs-e2e-tests
    jira/project-key: COMINS
    pagerduty.com/service-id: PYVA89L
    twilio.com/email: team_messaging-postflight@twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'true'
    twilio.com/in-scope-sox: 'true'
    twilio.com/ldap-group: team_messaging-postflight
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: communication-logs-alerts-stage
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/communication-logs-e2e-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-communication-logs-e2e-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/communication-logs-e2e-tests-iac
  tags:
  - hipaa
  - pci
  - sox
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-3134
  system: messaging-postflight