apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: communication-logs-load-tests
  title: communication-logs-load-tests
  description: Load generator role for communication logs team
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/communication-logs-load-tests
    github.com/project-slug: twilio/communication-logs-load-tests
    pagerduty.com/service-id: PHOWIEY
    twilio.com/email: team_communication-logs@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
  links: []
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-3134
  system: communication-logs-auxiliary