apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deliverability-score-api
  title: deliverability-score-api
  description: Deliverability Score API for CDE initiative
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/deliverability-score-api
    github.com/project-slug: messaging/deliverability-score-api
    pagerduty.com/service-id: PAC7IAC
    twilio.com/email: team_messaging-customer-growth@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P883LB8
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/deliverability-score-api-deploy
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-2040
  system: deliverability-score
  dependsOn:
  - component:default/accounts-api