kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2040"
  system: messaging-delivery-and-engagement-insights
  lifecycle: production
metadata:
  name: dr-backfill-clickhouse-executor
  tags:
    - messaging
  title: dr-backfill-clickhouse-executor
  annotations:
    twilio.com/email: team_messaging-insights@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PBFDZ8P
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: PWS471W
  description: Role for executing the DR/backfill spark job
apiVersion: backstage.io/v1alpha1