kind: Component
spec:
  type: service
  owner: "group:default/sup-org-3134"
  system: communication-logs-api
  lifecycle: production
metadata:
  name: logs-dr-backfill-clickhouse-executor
  title: logs-dr-backfill-clickhouse-executor
  annotations:
    twilio.com/email: messaging-communication-logs@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PHOWIEY
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: TBC
  description: Role to backfill Logs data into ClickHouse
apiVersion: backstage.io/v1alpha1