kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2040"
  system: msg-feedback-service
  dependsOn:
    - component:default/eventbus
    - component:default/ud-entity-schema-api
    - component:default/message-state-service
    - component:default/data-producer-api
    - component:default/channelorch-ems-api
  lifecycle: production
metadata:
  name: messaging-feedback-service
  links:
    -
      url: "https://github.com/twilio-internal/messaging-feedback-service-deploy"
      title: Deployment Repository
  title: messaging-feedback-service
  annotations:
    twilio.com/email: team_messaging-customer-growth@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PAC7IAC
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: P883LB8
  description: REST Service to handle messaging feedback related data
apiVersion: backstage.io/v1alpha1