kind: Component
spec:
  type: service
  owner: "group:default/sup-org-3134"
  system: communication-logs-auxiliary
  dependsOn:
    - component:default/propertystore-api
    - component:default/accounts-api
  lifecycle: production
metadata:
  name: messaging-dap-configuration-service
  links:
    -
      url: "https://github.com/twilio-internal/messaging-dap-configuration-service-deploy"
      title: Deployment Repository
  title: messaging-dap-configuration-service
  annotations:
    twilio.com/email: team_communication-logs@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PHOWIEY
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
  description: Messaging DAP Configuration Service
apiVersion: backstage.io/v1alpha1