kind: Component
spec:
  type: service
  owner: "group:default/sup-org-649"
  system: limits-store
  lifecycle: experimental
metadata:
  name: messaging-limits-store
  links:
    -
      url: "https://github.com/twilio-internal/messaging-limits-store-deploy"
      title: Deployment Repository
  title: messaging-limits-store
  annotations:
    twilio.com/email: team_messaging-throughput@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P4NPJP0
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P659T4H
  description: Messaging Limits Store service provides messaging-wide limits for channels
apiVersion: backstage.io/v1alpha1