kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2040"
  system: messaging-delivery-and-engagement-insights
  dependsOn:
    - component:default/ud-entity-schema-api
    - component:default/eventbus
  lifecycle: production
metadata:
  name: messaging-insights-mdr-omnichannel
  tags:
    - messaging
  title: messaging-insights-mdr-omnichannel
  annotations:
    twilio.com/email: team_messaging-insights@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PBFDZ8P
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PWS471W
  description: role supporting messaging insights for omnichannel messages
apiVersion: backstage.io/v1alpha1