apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-insights-dataset-manager
  title: messaging-insights-dataset-manager
  description: Orchestrates onboarding and maintenance tasks for Messaging Insights
    datasets.
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-insights-dataset-manager
    github.com/project-slug: twilio-internal/messaging-insights-dataset-manager
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    pagerduty.com/service-id: PBFDZ8P
    twilio.com/pd-incident-owner-schedule: PWS471W
    twilio.com/email: team_messaging-insights@twilio.com
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2040
  system: messaging-delivery-and-engagement-insights