apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-system
  title: notification-system
  description: Notification System. See [Design Doc](https://docs.google.com/document/d/1h6BXENoLxhnK1xgn4AC1DySNFMft6XF9x_bO4zWRhJU/edit?usp=sharing)
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/notification-system
    buildkite.com/project-slug: twilio/twilio-internal-notification-system
    github.com/project-slug: twilio-internal/notification-system
    jira/project-key: MCG
    pagerduty.com/service-id: PAC7IAC
    twilio.com/email: team_messaging-customer-growth@twilio.com
    twilio.com/ldap-group: team_messaging-customer-growth
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: eng-messaging-customer-growth
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/notification-system-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-notification-system
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/notification-system-iac
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-2040
  system: deliverability-score