apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ratequeue-redis-cluster
  title: ratequeue-redis-cluster
  description: Redis Cluster for the SMS Rate Limiting system
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/ratequeue-redis-cluster
    buildkite.com/project-slug: twilio/twilio-internal-ratequeue-redis-cluster
    github.com/project-slug: twilio-internal/ratequeue-redis-cluster
    jira/project-key: MSGQUEUING
    pagerduty.com/service-id: P4NPJP0
    twilio.com/email: team_messaging-queuing@twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'true'
    twilio.com/in-scope-sox: 'true'
    twilio.com/ldap-group: team_messaging-queuing
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-messaging-queuing
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/ratequeue-redis-cluster-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-ratequeue-redis-cluster
  - title: IaC Repository
    url: https://github.com/twilio-internal/ratequeue-redis-cluster-iac
  tags:
  - hipaa
  - pci
  - sox
  - stateful
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-649
  system: sms-rate-limiting