kind: Component
spec:
  type: service
  owner: "group:default/sup-org-649"
  system: sms-rate-limiting
  dependsOn:
    - component:default/sms-ratequeue-accounts-primary
    - component:default/sms-ratequeue-accounts-replica
    - component:default/nagios-frontend-v2
  lifecycle: production
metadata:
  name: sms-ratequeue-accounts-replica
  tags:
    - sms
  links:
    -
      url: "https://github.com/twilio-internal/sms-ratequeue-accounts-replica-deploy"
      title: Deployment Repository
  title: sms-ratequeue-accounts-replica
  annotations:
    twilio.com/email: team_messaging-queuing@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P4NPJP0
    twilio.com/security-tier: 2
    twilio.com/in-scope-hipaa: false
    twilio.com/pd-incident-owner-schedule: P3EUJ41
  description: Facilitates applying rate limits to an Accounts use of the SMS Messaging Channel (Replica to Primary)
apiVersion: backstage.io/v1alpha1