apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: throughput-rules-management
  title: throughput-rules-management
  description: Throughput Rules Management (TRM) service provides management capabilities
    to configure the Messaging Throughput Products.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/throughput-rules-management
    github.com/project-slug: messaging/throughput-rules-management
    pagerduty.com/service-id: P4NPJP0
    twilio.com/email: team_messaging-throughput@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: P659T4H
    twilio.com/security-tier: '2'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/throughput-rules-management-deploy
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-649
  system: limits-store
  dependsOn:
  - component:default/accounts-api
  - component:default/id-account-manager-service