apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: throughput-management-service-e2e-test
  title: throughput-management-service-e2e-test
  description: E2E throughput-management-service
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/throughput-management-service-e2e-test
    buildkite.com/project-slug: twilio/twilio-internal-throughput-management-service-e2e-test
    github.com/project-slug: twilio-internal/throughput-management-service-e2e-test
    jira/project-key: MSGTHRPUT
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_messaging-throughput@twilio.com
    twilio.com/ldap-group: team_messaging-throughput
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-messaging-throughput
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/throughput-management-service-e2e-test-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-throughput-management-service-e2e-test
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-649
  system: limits-store