apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: userdata-messaging-api
  title: userdata-messaging-api
  description: Federates inflight and postflight Message data for unified public API
    consumption
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/userdata-messaging-api
    github.com/project-slug: twilio/userdata-messaging-api
    pagerduty.com/service-id: PHOWIEY
    twilio.com/email: messaging-communication-logs@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: TBC
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '2'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/userdata-messaging-api-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-3134
  system: communication-logs-api
  dependsOn:
  - component:default/accounts-api
  - component:default/billing-gate-keeper
  - component:default/data-producer-api
  - component:default/feature-service
  - component:default/eventbus
  - component:default/id-encrypt-decrypt-service
  - component:default/messaging-inflight-service
  - component:default/postflight-messaging-api
  - component:default/propertystore-api