apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-bonanza
  title: comms-api-bonanza
  description: Comms API Bonanza
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-bonanza
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-bonanza
    github.com/project-slug: twilio-internal/comms-api-bonanza
    jira/project-key: LMN
    pagerduty.com/service-id: PBO3JTY
    twilio.com/email: team_comms-api-admin@twilio.com
    twilio.com/ldap-group: team_comms-api-admin
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: tmp-bonanza
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-bonanza-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-bonanza
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/comms-api-bonanza-iac
  tags:
  - mms
spec:
  type: service
  lifecycle: production
  owner: jm-sup-org-167
  system: comms-api-bonanza