apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-emails
  title: comms-api-emails
  description: Emails service for comms-api
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-emails
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-emails
    github.com/project-slug: twilio-internal/comms-api-emails
    jira/project-key: LMN
    pagerduty.com/service-id: PVDBMLJ
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/ldap-group: team_messaging-bulk
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: eng-messaging-bulk
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-emails-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-emails
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/comms-api-emails-iac
  tags:
  - mms
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: comms-api-emails