apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-broadcast-internal-api
  title: comms-api-broadcast-internal-api
  description: Service deployed in comms-api cluster to bridge comms-api-messages and messaging-broadcast-api services, enabling 1:n messaging.
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-broadcast-internal-api
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-broadcast-internal-api
    github.com/project-slug: twilio-internal/comms-api-broadcast-internal-api
    jira/project-key: replace-me
    pagerduty.com/service-id: replace-me
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/ldap-group: team_messaging-bulk
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: replace-me
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-broadcast-internal-api-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-broadcast-internal-api
  tags:
  - stateful
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446