apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-messages-tests
  title: comms-api-messages-tests
  description: The integration tests for comms-api messaging domain services
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-messages-tests
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-messages-tests
    github.com/project-slug: twilio-internal/comms-api-messages-tests
    jira/project-key: LMN
    pagerduty.com/service-id: P8NGS3M
    twilio.com/email: team_comms-messages@twilio.com
    twilio.com/ldap-group: team_comms-messages
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-serrano
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-messages-tests-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-messages-tests
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/comms-api-messages-tests-iac
  tags:
  - mms
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-2446
  system: comms-api-messages-tests