apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-contacts
  title: comms-api-contacts
  description: Repository created by Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-contacts
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-contacts
    github.com/project-slug: twilio-internal/comms-api-contacts
    jira/project-key: CONCORE
    pagerduty.com/service-id: PW6CPHN
    twilio.com/email: team_convo-edge@twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-sox: 'true'
    twilio.com/ldap-group: team_convo-edge
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-convo-engine
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-contacts-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-contacts
  tags:
  - hipaa
  - sox
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2824
  system: system:default/system-conversation-management