apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comms-api-relay
  title: comms-api-relay
  description: Relays for Comms API
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/comms-api-relay
    buildkite.com/project-slug: twilio/twilio-internal-comms-api-relay
    github.com/project-slug: twilio-internal/comms-api-relay
    jira/project-key: LMN
    pagerduty.com/service-id: PUWX68D
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/ldap-group: team_messaging-bulk
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: tmp-serrano-relays
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/comms-api-relay-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-comms-api-relay
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/comms-api-relay-iac
  tags:
  - mms
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: comms-api-relay