apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emails-service
  title: emails-service
  description: Repository created by Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/emails-service
    buildkite.com/project-slug: twilio/twilio-internal-emails-service
    github.com/project-slug: twilio-internal/emails-service
    jira/project-key: LMN
    pagerduty.com/service-id: PVDBMLJ
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/ldap-group: team_messaging-bulk
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: eng-messaging-bulk
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/emails-service-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-emails-service
  tags:
  - mms
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: comms-api-emails