apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: history-search-service
  title: history-search-service
  description: History Search Service enables ...
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/history-search-service
    buildkite.com/project-slug: twilio/messaging/history-search-service
    github.com/project-slug: messaging/history-search-service
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    twilio.com/slack-id: C016RLP969K
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/history-search-service-deploy
  tags:
  - history-search-service
  - java17
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: mdp-business-events-system