apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mdp-schema-automation
  title: mdp-schema-automation
  description: MDP Schema Automation is schema pipeline.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/mdp-schema-automation
    buildkite.com/project-slug: twilio/messaging/mdp-schema-automation
    github.com/project-slug: messaging/mdp-schema-automation
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/pd-incident-owner-schedule: PR5HVZL
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-id: C016RLP969K
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/mdp-schema-automation-deploy
  tags:
  - java17
  - mdp-schema-automation
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: mdp-business-events-system
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus