apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mdp-event-client-load-tester
  title: mdp-event-client-load-tester
  description: MDP Event Client Load Tester is a collection of load testing tools
    for the Messaging Data Platform (MDP) event client.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/mdp-event-client-load-tester
    buildkite.com/project-slug: twilio/messaging/mdp-event-client-load-tester
    github.com/project-slug: messaging/mdp-event-client-load-tester
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/pd-incident-owner-schedule: PR5HVZL
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-id: C016RLP969K
  links: []
  tags:
  - java17
  - mdp-event-client
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: mdp-business-events-system
  dependsOn:
  - component:default/ud-entity-schema-api
  - component:default/eventbus