apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mdp-data-relays-infra
  title: mdp-data-relays-infra
  description: MDP Data Relays Infrastructure Repository
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/mdp-data-relays-infra
    buildkite.com/project-slug: twilio/twilio-internal-mdp-data-relays-infra
    github.com/project-slug: twilio-internal/mdp-data-relays-infra
    jira/project-key: MDP
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/ldap-group: team_messaging-data-infra
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-channel-name: eng-messaging-data-platform
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/mdp-data-relays-infra-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-mdp-data-relays-infra
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: mdp-data-relay-system