apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mdp-pf-event-publisher
  title: mdp-pf-event-publisher
  description: MDP PF Event Publisher is a service that publishes finalized MDRs to
    Kafka using a legacy message format.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/mdp-pf-event-publisher
    buildkite.com/project-slug: twilio/messaging/mdp-pf-event-publisher
    github.com/project-slug: messaging/mdp-pf-event-publisher
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/pd-incident-owner-schedule: PR5HVZL
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '3'
    twilio.com/slack-id: C016RLP969K
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/mdp-pf-event-publisher-deploy
  tags:
  - java17
  - mdp-pf-event-publisher
  - messaging
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: mdp-business-events-system
  dependsOn:
  - component:default/eventbus
  - component:default/ud-entity-schema-api