apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-scheduler-api
  title: messaging-scheduler-api
  description: Repository created by Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-scheduler-api
    buildkite.com/project-slug: twilio/twilio-internal-messaging-scheduler-api
    github.com/project-slug: twilio-internal/messaging-scheduler-api
    jira/project-key: MTCES-1306
    pagerduty.com/service-id: P6QZ8RE
    twilio.com/email: team_mtc@twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-sox: 'true'
    twilio.com/ldap-group: team_mtc
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-mtc
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/messaging-scheduler-api-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-messaging-scheduler-api
  tags:
  - hipaa
  - sox
  - stateful
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: system:default/system-messaging-scheduler