apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-bulk-load-generator
  title: messaging-bulk-load-generator
  description: Generate load for load test for messaging-bulk
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/messaging-bulk-load-generator
    github.com/project-slug: twilio/messaging-bulk-load-generator
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
  links: []
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: messaging-bulk