apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-incoming-gateway
  title: messaging-incoming-gateway
  description: Router MO SMS Messages
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/messaging-incoming-gateway
    github.com/project-slug: twilio/messaging-incoming-gateway
    jira/project-key: EGN
    pagerduty.com/service-id: PZ6W2KR   # Engine Prod Service
    twilio.com/email: team_engine@twilio.com
    twilio.com/ldap-group: team_engine
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
    twilio.com/data-classification: 'confidential'
    twilio.com/internet-facing: 'false'
    twilio.com/eu-available: 'true'
    twilio.com/sla-impacting: 'true'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/in-scope-soc2: 'false'
    twilio.com/in-scope-iso: 'false'
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/messaging-incoming-gateway-deploy
    - title: IaC Repository
      url: https://code.hq.twilio.com/messaging/messaging-incoming-gateway-terraform
  tags:
    - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2824
  system: inbound-messaging
  dependsOn:
    - component:default/number-validation-service
    - component:default/messaging-number-pool-service
    - component:default/inventory-caching-service
    - component:default/sms-dlr-ack-gateway
    - component:default/carrierops-provider-service
    - component:default/pied-piper-ingest
    - component:default/eventbus
    - component:default/consumer-trust-configs-service
    - component:default/inventory-testing-endpoints-service
    - component:default/accounts-api
    - component:default/messaging-ratequeue-ext2-master
    - component:default/messaging-ratequeue-ext2-slave
    - component:default/ud-entity-schema-api
    - component:default/message-state-service