kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1777"
  system: event-stream-status-updates
  dependsOn:
    - component:default/eventbus
    - component:default/ud-entity-schema-api
    - component:default/twiml-application-service
    - component:default/accounts-api
  lifecycle: production
metadata:
  name: messaging-mdr-event-streams-adapter
  tags:
    - messaging
  links:
    -
      url: "https://code.hq.twilio.com/messaging/mdr-es-adapter-terraform"
      title: IaC Repository
    -
      url: "https://buildkite.com/twilio/messaging-mdr-event-streams-adapter"
      title: Buildkite Pipeline
    -
      url: "https://github.com/twilio-internal/messaging-mdr-event-streams-adapter-deploy"
      title: Deployment Repository
    -
      url: "https://code.hq.twilio.com/messaging/mcitll-e2e-monitors"
      title: E2E Tests Repository
    -
      url: "https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382783807/messaging-mdr-event-streams-adapter"
      title: Runbook
  title: messaging-mdr-event-streams-adapter
  annotations:
    twilio.com/email: team_msgorch@twilio.com
    twilio.com/eu-available: false
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: false
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: PA9T2AV
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: false
    twilio.com/security-tier: 0
    twilio.com/sla-impacting: true
    twilio.com/in-scope-hipaa: true
    twilio.com/internet-facing: false
    twilio.com/data-classification: restricted
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
  description: Adapter that consumes MDR updates, maps them to Event Streams notifications and publishes it to Event Streams Kafka topic.
apiVersion: backstage.io/v1alpha1