apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-load-tester
  title: messaging-load-tester
  description: Messaging APIs load testing infrastructure
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-load-tester
    buildkite.com/project-slug: twilio/twilio-internal-messaging-load-tester
    github.com/project-slug: twilio-internal/messaging-load-tester
    jira/project-key: MDP
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/ldap-group: team_messaging-data-infra
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: eng-messaging-data-platform
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-load-tester-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-messaging-load-tester
spec:
  type: service
  lifecycle: experimental
  owner: jm-sup5.30
  system: mdp-state-management-system