apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-inflight-service
  title: messaging-inflight-service
  description: Messaging Inflight Service manages and tracks inflight messages for
    the Messaging Data Platform (MDP).
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/twilio/messaging-inflight-service
    buildkite.com/project-slug: twilio/messaging/resr-taf-migration/messaging-inflight-service
    github.com/project-slug: twilio/messaging-inflight-service
    pagerduty.com/service-id: P8G5P66
    twilio.com/email: team_messaging-data-infra@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/pd-incident-owner-schedule: PR5HVZL
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    twilio.com/slack-id: C016RLP969K
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-inflight-service-deploy
  tags:
  - java17
  - messaging
  - messaging-inflight-service
spec:
  type: service
  lifecycle: production
  owner: jm-sup5.30
  system: messaging-inflight