apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-broadcast-api
  title: messaging-broadcast-api
  description: Exposes a JSON interface over HTTPS to support all broadcast functionality.
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-broadcast-api
    buildkite.com/project-slug: twilio/twilio-internal-messaging-broadcast-api
    github.com/project-slug: twilio-internal/messaging-broadcast-api
    jira/project-key: MSGBC
    pagerduty.com/service-id: ${{ parameters.pagerDutyId | trim }}
    twilio.com/email: team_messaging-bulk@twilio.com
    twilio.com/ldap-group: team_messaging-bulk
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-messaging-bulk
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/messaging-broadcast-api-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-messaging-broadcast-api
  - title: IaC Repository
    url: https://github.com/twilio-internal/messaging-broadcast-api-terraform
  tags:
  - stateful
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446