apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: message-receipt-processor
  title: message-receipt-processor
  description: message-receipt-processor is responsible for processing message receipts (like Delivery Receipts (DLRs)) pertaining to recently sent outbound messages
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/message-receipt-processor
    buildkite.com/project-slug: twilio/twilio-internal-message-receipt-processor
    github.com/project-slug: twilio-internal/message-receipt-processor
    jira/project-key: SMSCORE
    pagerduty.com/service-id: P4NPJP0
    twilio.com/email: team_sms-core@twilio.com
    twilio.com/in-scope-hipaa: 'true'
    twilio.com/ldap-group: team_sms-core
    twilio.com/security-tier: '1'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: eng-message-flow
  links:
  - title: Deployment Repository
    url: https://www.github.com/twilio-internal/message-receipt-processor-deploy
  - title: Buildkite Pipeline
    url: https://www.buildkite.com/twilio/twilio-internal-message-receipt-processor
  - title: IaC Repository
    url: https://www.github.com/twilio-internal/message-receipt-processor-iac
  tags:
  - hipaa
  - stateful
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-1358
  system: messaging-dlr