apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-bulk-send
  title: messaging-bulk-send
  description: 'Serves the Bulk Messaging Interface that enables 1:Many (recipients) message creation requests'
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-bulk-send
    github.com/project-slug: twilio-internal/messaging-bulk-send
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/email: team_messaging-bulk@twilio.com
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/messaging-bulk-send-deploy
  tags:
  - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-2446
  system: messaging-bulk