apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-webhook-testing
  title: messaging-webhook-testing
  description: Testing service for webhooks.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/messaging-webhook-testing
    github.com/project-slug: messaging/messaging-webhook-testing
    pagerduty.com/service-id: PA9T2AV
    twilio.com/email: team_msgorch@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/data-classification: 'restricted'
    twilio.com/internet-facing: 'true'
    twilio.com/eu-available: 'false'
    twilio.com/sla-impacting: 'true'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/in-scope-soc2: 'false'
    twilio.com/in-scope-iso: 'false'
  links:
    - title: IaC Repository
      url: https://code.hq.twilio.com/messaging/messaging-webhook-testing-terraform
    - title: Buildkite Pipeline
      url: https://buildkite.com/twilio/messaging-messaging-webhook-testing
    - title: Deployment Repository
      url: https://github.com/twilio-internal/messaging-webhook-testing-deploy
    - title: Runbook
      url: https://twilio-productivity.atlassian.net/wiki/spaces/RT/pages/382771328/messaging-webhook-testing
  tags:
    - messaging
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-1777
  system: messaging-webhook-testing