kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2446"
  system: message-traffic-control-service
  dependsOn:
    - component:default/eventbus
    - component:default/message-state-service
    - component:default/messaging-msg-send
    - component:default/messaging-inflight-service
  lifecycle: production
metadata:
  name: mtc-sgs-app
  tags:
    - messaging
  title: mtc-sgs-app
  annotations:
    twilio.com/email: team-mtc@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P6QZ8RE
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PFXZBE9
  description: K8s based services supporting Scheduled Messaging (sgs worker pods)
apiVersion: backstage.io/v1alpha1