kind: Component
spec:
  type: service
  owner: "group:default/sup-org-2824"
  system: notification-services
  lifecycle: production
metadata:
  name: rtd-data-delivery
  links:
    -
      url: "https://github.com/twilio-internal/rtd-data-delivery-deploy"
      title: Deployment Repository
  title: rtd-data-delivery
  annotations:
    twilio.com/email: conversations_edge_east@twilio.com
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 1
    pagerduty.com/service-id: P3PWPTV
    twilio.com/security-tier: 0
    twilio.com/in-scope-hipaa: true
    twilio.com/pd-incident-owner-schedule: PT3ETZO
  description: Data delivery service
apiVersion: backstage.io/v1alpha1