apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sms-test-event-queue
  title: sms-test-event-queue
  description: Used to queue mock provider and callback events for cluster tests.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/sms/sms-test-event-queue
    github.com/project-slug: sms/sms-test-event-queue
    pagerduty.com/service-id: P4NPJP0
    twilio.com/email: sms-core@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/pd-incident-owner-schedule: PFBNAIJ
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
  links:
  - title: Deployment Repository
    url: https://github.com/twilio-internal/sms-test-event-queue-deploy
  tags:
  - sms
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1358
  system: sms-outbound-test-infrastructure