apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sms-outbound-e2e-tests
  title: sms-outbound-e2e-tests
  description: SMS outbound E2E tests.
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/routing-integration-tests
    buildkite.com/project-slug: twilio/sms-outbound-e2e-tests
    github.com/project-slug: messaging/routing-integration-tests
    twilio.com/github-server: code.hq.twilio.com
    jira/project-key: SMSCORE
    twilio.com/email: team_sms-core@twilio.com
    twilio.com/ldap-group: team_sms-core
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '4'
    twilio.com/slack-channel-name: eng-message-flow
    twilio.com/data-classification: "confidential"
    twilio.com/internet-facing: "false"
    twilio.com/sla-impacting: "false"
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/eu-available: "false"
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/sms-outbound-e2e-tests-deploy
    - title: Buildkite Pipeline
      url: https://buildkite.com/twilio/sms-outbound-e2e-tests
  tags:
    - sms
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-1358
  system: sms-outbound-test-infrastructure