apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: channels-external-proxy
  title: channels-external-proxy
  description: Channels External Proxy is a service that acts as an intermediary for messaging channels internal Twilio services and the internet
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/channels-external-proxy
    buildkite.com/project-slug: twilio/messaging-channels-external-proxy
    github.com/project-slug: messaging/channels-external-proxy
    github.com/team-slug: twilio-internal/team_messaging-channels
    pagerduty.com/service-id: PS1CR97
    twilio.com/data-classification: "confidential"
    twilio.com/email: team_messaging-channels@twilio.com
    twilio.com/eu-available: "false"
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-bcr: "false"
    twilio.com/in-scope-gdpr: "false"
    twilio.com/in-scope-hipaa: "false"
    twilio.com/in-scope-iso: "false"
    twilio.com/in-scope-pci: "false"
    twilio.com/in-scope-soc2: "false"
    twilio.com/in-scope-sox: "false"
    twilio.com/internet-facing: "false"
    twilio.com/ldap-group: team_messaging-channels
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/sla-impacting: "false"
    twilio.com/slack-channel-name: "#eng-messaging-channels"
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/channels-external-proxy-deploy
    - title: Buildkite Pipeline
      url: https://www.buildkite.com/twilio/messaging-channels-external-proxy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup_org_zip-823
  system: sender-management