kind: Component
spec:
  type: service
  owner: "group:default/sup-org-484"
  system: sender-management
  lifecycle: experimental
metadata:
  name: ci-messaging-integration-tests
  title: ci-messaging-integration-tests
  annotations:
    twilio.com/email: messaging-channels@twilio.com
    twilio.com/eu-available: false
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: false
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: false
    twilio.com/service-tier: 3
    pagerduty.com/service-id: PS1CR97
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: false
    twilio.com/security-tier: 2
    twilio.com/sla-impacting: false
    twilio.com/in-scope-hipaa: false
    twilio.com/internet-facing: false
    twilio.com/data-classification: confidential
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
  description: Admiral role for CI to assume IAM role to test messaging-integration-tests
apiVersion: backstage.io/v1alpha1