apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-ott-storehouse-cluster-tests
  title: messaging-ott-storehouse-cluster-tests
  description: Cluster tests for messaging-ott-storehouse
  annotations:
    backstage.io/source-location: url:https://github.com/twilio-internal/messaging-ott-storehouse-cluster-tests
    buildkite.com/project-slug: twilio/twilio-internal-messaging-ott-storehouse-cluster-tests
    github.com/project-slug: twilio-internal/messaging-ott-storehouse-cluster-tests
    pagerduty.com/service-id: PJSPQ3P
    twilio.com/data-classification: 'confidential'
    twilio.com/eu-available: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-iso: 'false'
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-soc2: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/internet-facing: 'false'
    twilio.com/sla-impacting: 'false'
    twilio.com/email: team_messaging-channels@twilio.com
    twilio.com/ldap-group: team_messaging-channels
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '5'
    twilio.com/slack-channel-name: eng-messaging-channels-content
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/messaging-ott-storehouse-cluster-tests-deploy
    - title: Buildkite Pipeline
      url: https://www.buildkite.com/twilio/twilio-internal-messaging-ott-storehouse-cluster-tests
    - title: IaC Repository
      url: https://github.com/twilio-internal/messaging-ott-storehouse-cluster-tests-iac
  tags:
    - messaging
spec:
  type: service
  lifecycle: experimental
  owner: group:default/sup-org-484
  system: messaging-channels-platform