kind: Component
spec:
  type: service
  owner: "group:default/sup-org-1644"
  system: whatsapp-messaging
  dependsOn:
    - component:default/message-state-service
    - component:default/message-state-service
  lifecycle: production
metadata:
  name: messaging-ott-whatsapp-utility-api
  title: messaging-ott-whatsapp-utility-api
  annotations:
    twilio.com/email: messaging-channels@twilio.com
    twilio.com/eu-available: false
    twilio.com/in-scope-bcr: false
    twilio.com/in-scope-iso: false
    twilio.com/in-scope-pci: false
    twilio.com/in-scope-sox: true
    twilio.com/service-tier: 1
    pagerduty.com/service-id: PS1CR97
    twilio.com/in-scope-gdpr: false
    twilio.com/in-scope-soc2: false
    twilio.com/security-tier: 0
    twilio.com/sla-impacting: false
    twilio.com/in-scope-hipaa: false
    twilio.com/internet-facing: false
    twilio.com/data-classification: confidential
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
  description: Messaging OTT channel Whatsapp utility APIs
apiVersion: backstage.io/v1alpha1