apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging-whatsapp-k8s-orch
  title: messaging-whatsapp-k8s-orch
  description: WhatsApp Container Orchestration with k8s cluster
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/whatsapp-k8s-orch
    github.com/project-slug: messaging/whatsapp-k8s-orch
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'false'
    twilio.com/security-tier: '2'
    twilio.com/service-tier: '1'
    pagerduty.com/service-id: PS1CR97
    twilio.com/data-classification: 'confidential'
    twilio.com/eu-available: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-iso: 'false'
    twilio.com/in-scope-soc2: 'false'
    twilio.com/internet-facing: 'false'
    twilio.com/sla-impacting: 'false'
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
    twilio.com/email: messaging-channels@twilio.com
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/messaging-whatsapp-k8s-orch-deploy
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-484
  system: sender-management
  dependsOn:
    - component:default/stock-clerk-service
    - component:default/userdata-messaging-api
    - component:default/messaging-ott-storehouse
    - component:default/inventory-federation-service
    - component:default/accounts-api
    - component:default/messaging-channel-emulators
    - component:default/feature-service
    - component:default/messaging-ratequeue-ott-master
    - component:default/eventbus
    - component:default/ud-entity-schema-api
    - component:default/template-management-store
    - component:default/pied-piper-ingest
    - component:default/data-producer-api
    - component:default/data-producer-api
    - component:default/messaging-scheduler-service-whatsapp-master
    - component:default/messaging-scheduler-service-whatsapp-slave
    - component:default/messaging-template-orch