apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: template-management-store
  title: template-management-store
  description: Service to manage templates for content-template
  annotations:
    backstage.io/source-location: url:https://code.hq.twilio.com/messaging/template-management-store
    buildkite.com/project-slug: twilio/messaging-template-management-store
    github.com/project-slug: messaging/template-management-store
    github.com/team-slug: twilio-internal/team_messaging-channels
    pagerduty.com/service-id: PS1CR97
    twilio.com/data-classification: 'confidential'
    twilio.com/eu-available: 'false'
    twilio.com/in-scope-bcr: 'false'
    twilio.com/in-scope-gdpr: 'false'
    twilio.com/in-scope-iso: 'false'
    twilio.com/in-scope-soc2: 'false'
    twilio.com/internet-facing: 'false'
    twilio.com/sla-impacting: 'false'
    twilio.com/email: team_messaging-channels@twilio.com
    twilio.com/github-server: code.hq.twilio.com
    twilio.com/in-scope-hipaa: 'false'
    twilio.com/in-scope-pci: 'false'
    twilio.com/in-scope-sox: 'true'
    twilio.com/ldap-group: team_messaging-channels
    twilio.com/pd-incident-owner-schedule: PQCIWQ1
    twilio.com/security-tier: '0'
    twilio.com/service-tier: '1'
    twilio.com/slack-channel-name: '#eng-messaging-channels'
  links:
    - title: Deployment Repository
      url: https://github.com/twilio-internal/template-management-store-deploy
    - title: Buildkite Pipeline
      url: https://www.buildkite.com/twilio/messaging-template-management-store
  tags:
    - sox
spec:
  type: service
  lifecycle: production
  owner: group:default/sup-org-1644
  system: content-template
  dependsOn:
    - component:default/contentstore
    - component:default/eventbus
    - component:default/data-producer-api
    - component:default/ud-entity-schema-api
    - component:default/accounts-api
    - component:default/feature-service