apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: backstage-plugin-region-builder
  title: backstage-plugin-region-builder
  description: "backstage-plugin-region-builder service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/backstage-plugin-region-builder