apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: capi-argo-cd-registrar
  title: capi-argo-cd-registrar
  description: "capi-argo-cd-registrar service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/capi-argo-cd-registrar