apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: cge-general-alertmanager-gitops
  title: cge-general-alertmanager-gitops
  description: "cge-general-alertmanager-gitops service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/cge-general-alertmanager-gitops