apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: demo-charlotte-july22-2024
  title: demo-charlotte-july22-2024
  description: "demo-charlotte-july22-2024 service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/demo-charlotte-july22-2024