apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: docker-k8s-operator-sdk
  title: docker-k8s-operator-sdk
  description: "docker-k8s-operator-sdk service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/docker-k8s-operator-sdk