apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: elasticache-redis-cluster-proxy
  title: elasticache-redis-cluster-proxy
  description: "elasticache-redis-cluster-proxy service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/elasticache-redis-cluster-proxy