apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: go-code-metrics-buildkite-plugin
  title: go-code-metrics-buildkite-plugin
  description: "go-code-metrics-buildkite-plugin service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/go-code-metrics-buildkite-plugin