apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: gobenchapi
  title: gobenchapi
  description: "gobenchapi service for SendGrid open source or integration."
  tags:
    - email
    - gobenchapi
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/gobenchapi