apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: helm-redis-failover-operator
  title: helm-redis-failover-operator
  description: "helm-redis-failover-operator service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-redis-failover-operator