apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: helm-core-cortex-tenant
  title: helm-core-cortex-tenant
  description: "helm-core-cortex-tenant service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/helm-core-cortex-tenant