apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: holocron-provisioner-live-image
  title: holocron-provisioner-live-image
  description: "holocron-provisioner-live-image service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/holocron-provisioner-live-image