apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: identity-cloud-migration-docs
  title: identity-cloud-migration-docs
  description: "identity-cloud-migration-docs service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/identity-cloud-migration-docs