apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: ironic-inspector-image-clone
  title: ironic-inspector-image-clone
  description: "ironic-inspector-image-clone service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/ironic-inspector-image-clone