apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: ironic_image
  title: ironic_image
  description: "ironic_image service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/ironic_image