apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: kustomize-test-render-manifests
  title: kustomize-test-render-manifests
  description: "kustomize-test-render-manifests service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/kustomize-test-render-manifests