apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: local-volume-operator
  title: local-volume-operator
  description: "local-volume-operator service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/local-volume-operator