apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: multibloom
  title: multibloom
  description: "MultiBloom service for SendGrid open source or integration."
  tags:
    - email
    - multibloom
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/multibloom