apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: sendgrid_inventory_livecd
  title: sendgrid_inventory_livecd
  description: "sendgrid_inventory_livecd service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/sendgrid_inventory_livecd