apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: sendgrid-ops-terraform-cluster-api-mgmt
  title: sendgrid-ops-terraform-cluster-api-mgmt
  description: "sendgrid-ops-terraform-cluster-api-mgmt service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/sendgrid-ops-terraform-cluster-api-mgmt