apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: smtpapi-objc
  title: smtpapi-objc
  description: "SMTPAPI Objective-C referencing cge-proxysql for deployment context."
  tags:
    - email
    - objc
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/smtpapi-objc