apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: splunkresult_to_sgevent
  title: splunkresult_to_sgevent
  description: "splunkresult_to_sgevent service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/splunkresult_to_sgevent