apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: swathi-test-gitsubmodules
  title: swathi-test-gitsubmodules
  description: "swathi-test-gitsubmodules service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/swathi-test-gitsubmodules