apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: terraform-capa-ami-backup
  title: terraform-capa-ami-backup
  description: "terraform-capa-ami-backup service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-capa-ami-backup