apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: terraform-eng-topsc-oidc
  title: terraform-eng-topsc-oidc
  description: "terraform-eng-topsc-oidc service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-eng-topsc-oidc