apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: "sup-org-2324"
metadata:
  name: visual_studio_sdk_mail
  title: visual_studio_sdk_mail
  description: "visual_studio_sdk_mail service for SendGrid integration."
  tags:
    - email
    - unmapped
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/visual_studio_sdk_mail