apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  providesApis:
  - ams-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/ams
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/ams/blob/main/README.md
    buildkite.com/project-slug: sendgrid/ams
    github.com/project-slug: sendgrid/ams
    jira/component: AMS
    jira/project-key: CLKRAKEN
    pagerduty.com/service-id: PLGIDLW
    snyk.io/target-id: sendgrid/ams
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
    twilio.com/email: eng-Kraken_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "2"
    twilio.com/slack-id: C03CLFJPS49
  links:
  - title: Runbook
    url: https://github.com/sendgrid/ams/blob/main/docs/runbook.md
  name: ams
  title: ams
  description: "AMS is a group of microservices which update customer accounts"
  tags:
  - email
  - ams
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ams-api
  description: "AMS is a group of microservices which update customer accounts"
  tags:
  - email
  - ams-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  definition:
    $text: https://github.com/sendgrid/ams/blob/main/reference/ams.messaging.yml