apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  providesApis:
  - chaos-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/chaos
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/chaos/blob/main/README.md
    buildkite.com/project-slug: sendgrid/chaos
    github.com/project-slug: sendgrid/chaos
    jira/component: Chaos
    jira/project-key: CLKRAKEN
    pagerduty.com/service-id: PEUID7M
    snyk.io/target-id: sendgrid/chaos
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
    twilio.com/email: eng-Kraken_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "2"
    twilio.com/slack-id: C03CLFJPS49
  links:
  - title: Runbook
    url: https://github.com/sendgrid/chaos/blob/main/docs/runbook.md
  name: chaos
  title: chaos
  description: "chaos is source of user and account information."
  tags:
  - email
  - chaos
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: chaos-api
  description: "chaos is a source of user and account information."
  tags:
  - email
  - chaos-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  definition:
    $text: https://github.com/sendgrid/chaos/blob/main/reference/chaos.v1.yaml