apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/chef-go-segment-riak
  title: chef-go-segment-riak
  description: "chef-go-segment-riak service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: chef-go-segment-riak