apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/cl-snowflake-sqlizer/blob/main/README.md
    github.com/project-slug: sendgrid/cl-snowflake-sqlizer
    buildkite.com/project-slug: sendgrid/cl-snowflake-sqlizer
    snyk.io/target-id: sendgrid/cl-snowflake-sqlizer
    jira/project-key: CLRP
    jira/component: CL Snowflake SQLizer
    twilio.com/slack-id: CDKGS75TR
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/cl-snowflake-sqlizer
  links:
    - title: Runbook
      url: https://github.com/sendgrid/cl-snowflake-sqlizer/blob/main/docs/runbook.md
  name: cl-snowflake-sqlizer
  title: cl-snowflake-sqlizer
  description: "CL Snowflake SQLizer service for SQL transformation and processing"
  tags:
    - snowflake
    - sqlizer
    - terraform