apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: cp-event-bus
  providesApis:
    - cp-event-bus-api
    - cp-event-bus-schema
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/cp-event-bus
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/cp-event-bus/blob/main/README.md
    buildkite.com/project-slug: sendgrid/cp-event-bus
    github.com/project-slug: sendgrid/cp-event-bus
    jira/component: Control Plane Events Bus
    jira/project-key: CLRP
    pagerduty.com/service-id: PMOM5Y6
    snyk.io/target-id: sendgrid/cp-event-bus
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "true"
    twilio.com/security-tier: "0"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: CDKGS75TR
  links:
    - title: Runbook
      url: https://github.com/sendgrid/cp-event-bus/blob/main/docs/runbook.md
  name: cp-event-bus
  title: cp-event-bus
  description: >
    Control Plane Events Bus is an EventBridge-based eventing system intended to publish account lifecycle and other  control plane events to a variety of consumers, both in-domain and cross-domain.
  tags:
    - email
    - control-plane
    - eventbridge
    - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cp-event-bus-api
  description: >
    The Control Plane Events Bus API is an APIGW that enables producers to emit point events to the Control Plane Events Bus.
  tags:
    - email
    - control-plane
    - eventbridge
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: cp-event-bus
  definition:
    $text: https://github.com/sendgrid/cp-event-bus/blob/main/reference/cl-events.yml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cp-event-bus-schema
  description: >
    The Control Plane Events Bus Schema defines the structure of events that can be consumed from the Control Plane Events Bus.
  tags:
    - email
    - control-plane
    - eventbridge
spec:
  type: asyncapi
  lifecycle: production
  owner: sup-org-1923
  system: cp-event-bus
  definition:
    $text: https://github.com/sendgrid/cp-event-bus/blob/main/reference/eventbridge-schemas.yml