apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  providesApis:
  - email-accounts-platform-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/email-accounts-platform
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/email-accounts-platform/blob/main/README.md
    buildkite.com/project-slug: sendgrid/email-accounts-platform
    github.com/project-slug: sendgrid/email-accounts-platform
    jira/component: "Email Accounts Platform"
    jira/project-key: CLRP
    pagerduty.com/service-id: "P80BE2Y"
    snyk.io/target-id: sendgrid/email-accounts-platform
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "0"
    twilio.com/slack-id: CDKGS75TR
  links:
  - title: Runbook
    url: https://github.com/sendgrid/email-accounts-platform/blob/main/docs/runbook.md
  name: email-accounts-platform
  title: email-accounts-platform
  description: "Email Accounts Platform (EAP) API provides the core api for account management."
  tags:
  - email
  - email-accounts-platform
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: email-accounts-platform-api
  description: "Email Accounts Platform API is the gateway to internal Sendgrid services and constructs. It provides endpoints for account creation, plan upgrades/downgrades, and punitive state visibility
    and actions. This API is used by our marketplace facades and the Account Provisioning API known as Acorn."
  tags:
  - email
  - email-accounts-platform
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  definition:
    $text: https://github.com/sendgrid/email-accounts-platform/blob/main/reference/openapi.yml