apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/go-kube-hello-world-aldo
  title: go-kube-hello-world-aldo
  description: "go-kube-hello-world-aldo service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: go-kube-hello-world-aldo