apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/mc-sms-events-pipeline
  title: mc-sms-events-pipeline
  description: "MC SMS Events Pipeline service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: mc-sms-events-pipeline