apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/mc-twilio-api-proxy
  title: mc-twilio-api-proxy
  description: "mc-twilio-api-proxy service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: mc-twilio-api-proxy