apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/mc-yak-mariposa
  title: mc-yak-mariposa
  description: "MC Yak Mariposa service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: mc-yak-mariposa