kind: Component
spec:
  type: Infrastructure
  owner: sup-org-1923
  system: email-reseller-platform
  lifecycle: production
metadata:
  name: ocrud-gitops
  tags:
    - email
    - ocrud-gitops
  title: ocrud-gitops
  annotations:
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    snyk.io/target-id: sendgrid/ocrud-gitops
    twilio.com/slack-id: CDKGS75TR
    github.com/project-slug: sendgrid/ocrud-gitops
    twilio.com/service-tier: 5
    twilio.com/security-tier: 2
    backstage.io/techdocs-ref: "url:https://github.com/sendgrid/ocrud-gitops/blob/main/README.md"
    buildkite.com/project-slug: sendgrid/ocrud-gitops
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
  description: OCRUD GitOps is solely used to store Kubernetes manifests
apiVersion: backstage.io/v1alpha1