apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  providesApis:
  - ocrud-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/ocrud
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/ocrud/blob/main/README.md
    buildkite.com/project-slug: sendgrid/ocrud
    github.com/project-slug: sendgrid/ocrud
    jira/component: "OCRUD"
    jira/project-key: CLRP
    pagerduty.com/service-id: "PTAE3MJ"
    snyk.io/target-id: sendgrid/ocrud
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: CDKGS75TR
  links:
  - title: Runbook
    url: https://github.com/sendgrid/ocrud/blob/main/docs/runbook.md
  name: ocrud
  title: ocrud
  description: "OCRUD is an on-prem service running in Kubernetes that handles customer-lifecycle-related CRUD operations in mailDB."
  tags:
  - email
  - ocrud
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ocrud-api
  description: "OCRUD is a service responsible for performing basic operations on maildb."
  tags:
  - email
  - ocrud
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  definition:
    $text: https://github.com/sendgrid/ocrud/blob/main/reference/openapi.yml