kind: Component
spec:
  type: Infrastructure
  owner: sup-org-1923
  system: email-reseller-platform
  lifecycle: production
metadata:
  name: oes-to-snowflake
  tags:
    - email
    - oes-to-snowflake
  title: oes-to-snowflake
  annotations:
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    snyk.io/target-id: sendgrid/oes-to-snowflake
    twilio.com/slack-id: CDKGS75TR
    github.com/project-slug: sendgrid/oes-to-snowflake
    twilio.com/service-tier: 5
    twilio.com/security-tier: 2
    backstage.io/techdocs-ref: "url:https://github.com/sendgrid/oes-to-snowflake/blob/main/README.md"
    buildkite.com/project-slug: sendgrid/oes-to-snowflake
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
  description: OES to Snowflake is terraform configuration that supports the migration of package-related account data from DynamoDB to Snowflake
apiVersion: backstage.io/v1alpha1