apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-datalake"
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: eng-email-data-platform@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/parasite/blob/master/README.md
    github.com/project-slug: sendgrid/parasite
    buildkite.com/project-slug: sendgrid/parasite
    snyk.io/target-id: sendgrid/parasite
    pagerduty.com/service-id: "PZ0HBCK"
    jira/project-key: DPSG
    jira/component: "Parasite"
    twilio.com/slack-id: CDKSZDJ86
    twilio.com/alerting-slack-channel-id-stage: CDJA5JYF6
    twilio.com/alerting-slack-channel-id-prod: CDJA5JYF6
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/parasite
  name: parasite
  title: parasite
  description: "Parasite is a service to monitor the health of the Email Events Pipeline as it flows from Kafka to AWS to Snowflake."
  tags:
    - email
    - parasite
    - mp-events
    - go