apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  providesApis:
  - point-delete-system-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/pds
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/pds/blob/main/README.md
    buildkite.com/project-slug: sendgrid/pds
    github.com/project-slug: sendgrid/pds
    jira/component: "PDS"
    jira/project-key: CLRP
    pagerduty.com/service-id: "PNX9H55"
    snyk.io/target-id: sendgrid/pds
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "true"
    twilio.com/security-tier: "0"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: CDKGS75TR
  links:
  - title: Runbook
    url: https://github.com/sendgrid/pds/blob/main/docs/runbook.md
  name: point-delete-system
  title: point-delete-system
  description: "Point delete system allows the customers to erase the recipients email events data"
  tags:
  - email
  - point-delete-system
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: point-delete-system-api
  description: "API for Point Delete System - a system which collects 'Right of Erasure' requests from customer interfaces, distribute them to systems that store PII for consequential erasure."
  tags:
  - email
  - point-delete-system-api
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
  definition:
    $text: https://github.com/sendgrid/pds/blob/main/reference/openapi.yml