apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/policy-sentry-buildkite-plugin
  title: policy-sentry-buildkite-plugin
  description: "policy-sentry-buildkite-plugin service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: policy-sentry-buildkite-plugin