apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1923
metadata:
  annotations:
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/renovater/blob/main/README.md
    github.com/project-slug: sendgrid/renovater
    backstage.io/source-location: url:https://github.com/sendgrid/renovater
  name: renovater
  title: renovater
  description: "Renovater is ontains a Buildkite pipeline that will enable/disable Renovate on a given set of repositories in the sendgrid or sendgrid-ops GitHub organizations"
  tags:
    - email
    - renovate-bk-plugin