apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  providesApis:
  - reseller-account-data-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/reseller-account-data
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/reseller-account-data/blob/main/README.md
    buildkite.com/project-slug: sendgrid/reseller-account-data
    github.com/project-slug: sendgrid/reseller-account-data
    jira/component: "Reseller Account Data"
    jira/project-key: CLRF
    pagerduty.com/service-id: "PQH1UB3"
    snyk.io/target-id: sendgrid/reseller-account-data
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: CDKGS75TR
  links:
  - title: Runbook
    url: https://github.com/sendgrid/reseller-account-data/blob/main/docs/RUNBOOK.md
  name: reseller-account-data
  title: reseller-account-data
  description: "Reseller Account Data provides an interface access to reseller account information stored within DynamoDB"
  tags:
  - email
  - reseller-account-data
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reseller-account-data-api
  description: "Reseller Account Data provides an interface access to reseller account information stored within DynamoDB"
  tags:
  - email
  - reseller-account-data
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  definition:
    $text: https://github.com/sendgrid/reseller-account-data/blob/main/reference/openapi.yml