apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: email-reseller-platform
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/reseller-general-alertmanager-gitops/blob/main/README.md
    github.com/project-slug: sendgrid/reseller-general-alertmanager-gitops
    buildkite.com/project-slug: sendgrid/reseller-general-alertmanager-gitops
    snyk.io/target-id: sendgrid/reseller-general-alertmanager-gitops
    twilio.com/slack-id: CDKGS75TR
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/reseller-general-alertmanager-gitops
  name: reseller-general-alertmanager-gitops
  title: reseller-general-alertmanager-gitops
  description: " Reseller General Alertmanager Gitops used to store Kubernetes manifests"
  tags:
    - email
    - gitops
    - soc2