apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: email-reseller-platform
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "1"
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/reseller-general-alertmanager/blob/main/README.md
    github.com/project-slug: sendgrid/reseller-general-alertmanager
    buildkite.com/project-slug: sendgrid/reseller-general-alertmanager
    snyk.io/target-id: sendgrid/reseller-general-alertmanager
    twilio.com/slack-id: CDKGS75TR
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/reseller-general-alertmanager
  name: reseller-general-alertmanager
  title: reseller-general-alertmanager
  description: "Reseller General Alert Manager ontains the helm configuration for the AlertManagerConfig which is rendered and merged to https://github.com/sendgrid/reseller-general-alertmanager-gitops"
  tags:
    - email
    - monitoring
    - alerting
    - reseller