apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: library
  lifecycle: production
  owner: sup-org-1923
  system: email-reseller-platform
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/reseller-logger/blob/main/README.md
    github.com/project-slug: sendgrid/reseller-logger
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/reseller-logger
  name: reseller-logger
  title: reseller-logger
  description: "Reseller Logger Reseller Golang Library For Logging"
  tags:
    - email
    - reseller-logging
    - reseller