apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  providesApis:
  - reseller-facade-azure-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/reseller-facade-azure
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/reseller-facade-azure/blob/main/README.md
    buildkite.com/project-slug: sendgrid/reseller-facade-azure
    github.com/project-slug: sendgrid/reseller-facade-azure
    jira/component: "Reseller Facade Azure"
    jira/project-key: CLRF
    pagerduty.com/service-id: "PJIMYHH"
    snyk.io/target-id: sendgrid/reseller-facade-azure
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "0"
    twilio.com/slack-id: CDKGS75TR
  links:
  - title: Runbook
    url: https://github.com/sendgrid/reseller-facade-azure/blob/main/docs/runbook.md
  name: reseller-facade-azure
  title: reseller-facade-azure
  description: "Reseller Facade Azure is a service that provides an Azure saas marketplace integration with Twilio SendGrid."
  tags:
  - email
  - reseller-facade-azure
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reseller-facade-azure-api
  description: "The Reseller Facade Azure is a API for integrating the Azure SaaS Marketplace with Twilio SendGrid's email accounts platform."
  tags:
  - email
  - reseller-facade-azure
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  definition:
    $text: https://github.com/sendgrid/reseller-facade-azure/blob/main/reference/openapi.yml