apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-platform"
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/rolehop/blob/main/README.md
    github.com/project-slug: sendgrid/rolehop
    buildkite.com/project-slug: sendgrid/rolehop
    snyk.io/target-id: sendgrid/rolehop
    jira/project-key: CLRP
    jira/component: "Rolehop"
    twilio.com/slack-id: CDKGS75TR
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/rolehop
  name: rolehop
  title: rolehop
  description: "Rolehop rovides IAM role hopping functionality for use with the AWS Go SDKs"
  tags:
    - email
    - rolehop