apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  providesApis:
  - rome-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/rome-api
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/rome-api/blob/main/README.md
    buildkite.com/project-slug: sendgrid/rome-api
    github.com/project-slug: sendgrid/rome-api
    jira/component: "Rome API"
    jira/project-key: CLRF
    snyk.io/target-id: sendgrid/rome-api
    twilio.com/alerting-slack-channel-id-prod: CDKSZHQUW
    twilio.com/alerting-slack-channel-id-stage: C031JT6HNUE
    twilio.com/email: eng-resellerplatform_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "4"
    twilio.com/slack-id: CDKGS75TR
  name: rome-api
  title: rome-api
  description: "Rome API enables customer support partners to better understand their customers without engineering assistance."
  tags:
  - email
  - rome-api
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rome-api
  description: "Rome API enables customer support partners to better understand their customers without engineering assistance."
  tags:
  - email
  - rome-api
  - go
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1923
  system: "email-reseller-facade"
  definition:
    $text: https://github.com/sendgrid/rome-api/blob/main/reference/openapi.yml