apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  providesApis:
  - self-service-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/self-service-api
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/self-service-api/blob/main/README.md
    buildkite.com/project-slug: sendgrid/self-service-api
    github.com/project-slug: sendgrid/self-service-api
    jira/component: Self Service API
    jira/project-key: CLKRAKEN
    pagerduty.com/service-id: PMPBF54
    snyk.io/target-id: sendgrid/self-service-api
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
    twilio.com/email: eng-Kraken_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: C03CLFJPS49
  links:
  - title: Runbook
    url: https://github.com/sendgrid/self-service-api/blob/main/docs/RUNBOOK.md
  name: ssapi
  title: ssapi
  description: "Self Service API to integrate with the Customer Lifecycle Platform as the facade for direct customers."
  tags:
  - email
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: self-service-api
  description: "Self Service API to integrate with the Customer Lifecycle Platform as the facade for direct customers."
  tags:
  - email
  - self-service-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
  definition:
    $text: https://github.com/sendgrid/self-service-api/blob/main/reference/openapi.yml