apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  name: sisyphus
  title: sisyphus
  description: "sisyphus service for SendGrid integration."
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/sisyphus
  tags:
    - email
    - mc-orchestra