kind: Component
spec:
  type: Infrastructure
  owner: sup-org-1714
  system: email-account-management
  lifecycle: production
metadata:
  name: symmetra-gitops
  tags:
    - email
    - symmetra-gitops
  title: symmetra-gitops
  annotations:
    twilio.com/email: eng-Kraken_sg@twilio.com
    twilio.com/slack-id: CC03BSSZFPDF
    github.com/project-slug: sendgrid/symmetra-gitops
    twilio.com/service-tier: 5
    twilio.com/security-tier: 2
    backstage.io/techdocs-ref: "url:https://github.com/sendgrid/symmetra-gitops/blob/main/README.md"
    buildkite.com/project-slug: sendgrid/symmetra-gitops
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
  description: Symmetra GitOps serves as a deployment target for the symmetra Kubernetes manifests.
apiVersion: backstage.io/v1alpha1