apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1714
  system: email-account-management
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "5"
    twilio.com/email: eng-Kraken_sg@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/symmetra/blob/main/README.md
    github.com/project-slug: sendgrid/symmetra
    twilio.com/slack-id: CC03BSSZFPDF
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
    backstage.io/source-location: url:https://github.com/sendgrid/symmetra
  name: symmetra
  title: symmetra
  description: "Symmetra is another name for Debezium, a way to stream database changes to Kafka via Kafka Connect."
  tags:
    - email
    - symmetra