apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: Infrastructure
  lifecycle: production
  owner: sup-org-1923
  system: "email-datalake"
metadata:
  annotations:
    twilio.com/security-tier: "2"
    twilio.com/service-tier: "5"
    twilio.com/email: eng-email-data-platform@twilio.com
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/terraform-firehose-mds/blob/master/README.md
    github.com/project-slug: sendgrid/terraform-firehose-mds
    twilio.com/internet-facing: "false"
    backstage.io/source-location: url:https://github.com/sendgrid/terraform-firehose-mds
  name: terraform-firehose-mds
  title: terraform-firehose-mds
  description: "Terraform repo for AWS Data Firehose to MDS."
  tags:
    - email
    - data-platform
    - terraform