apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1421
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/terraform12-modules-msk
  title: terraform12-modules-msk
  description: "terraform12-modules-msk service for SendGrid integration."
  tags:
    - email
    - mc-orchestra
  name: terraform12-modules-msk