apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: sup-org-1714
  system: email-authorization
  providesApis:
  - tokenservice-api
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/sendgrid/tokenservice
    backstage.io/techdocs-ref: url:https://github.com/sendgrid/tokenservice/blob/main/README.md
    buildkite.com/project-slug: sendgrid/tokenservice
    github.com/project-slug: sendgrid/tokenservice
    jira/component: Token Service
    jira/project-key: CLRAM
    pagerduty.com/service-id: P3T3GYE
    snyk.io/target-id: sendgrid/tokenservice
    twilio.com/alerting-slack-channel-id-prod: C0233THSQE4
    twilio.com/email: eng-RAM_sg@twilio.com
    twilio.com/internet-facing: "false"
    twilio.com/security-tier: "1"
    twilio.com/service-tier: "1"
    twilio.com/slack-id: C03CLFJPS49
  links:
  - title: Runbook
    url: https://github.com/sendgrid/tokenservice/blob/main/docs/RUNBOOK.md
  name: tokenservice
  title: tokenservice
  description: "Token Service is a distributed system that is deployed on AWS infrastructure to provide tokens that can be used for token based authentication and one time authentication codes."
  tags:
  - email
  - authorization
  - go
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tokenservice-api
  description: "Token Service is a distributed system that is deployed on AWS infrastructure to provide tokens that can be used for token based authentication and one time authentication codes."
  tags:
  - email
  - tokenservice-api
spec:
  type: openapi
  lifecycle: production
  owner: sup-org-1714
  system: email-authorization
  definition:
    $text: https://github.com/sendgrid/tokenservice/blob/main/reference/openapi.yml