name: GH-Actions
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  CARGO_TERM_COLOR: always
jobs:
  frontend_service_build:
    runs-on: lunar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Node service tests
        run: |
          npm test
      - name: Snyk vulnerability scan
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk monitor --all-projects --project-name="frontend"
