name: GH-Actions
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  CARGO_TERM_COLOR: always
jobs:
  frontend_service_build:
    runs-on: lunar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          set-host: true
      - name: Node service tests
        run: |
          npm test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
