name: GH-Actions
on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: nacho-test
        steps:
            - name: Run Lunar CI Agent
              uses: earthly/lunar-ci-action@main
              env:
                LUNAR_HUB_TOKEN: ${{ secrets.LUNAR_LOCALDEV_HUB_TOKEN }}
                LUNAR_HUB_HOST: bf31-46-222-226-200.ngrok-free.app
            - name: Node service tests
              run: |
                env
                ls
